// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Asset                     string
	AssetType                 string
	EdgeGateway               string
	History                   string
	IotDevice                 string
	Organisation              string
	OriginatorClass           string
	ParamRepr                 string
	ParamReprAssetTypeMapping string
	ParamType                 string
	Telemetry                 string
}{
	Asset:                     "asset",
	AssetType:                 "asset_type",
	EdgeGateway:               "edge_gateway",
	History:                   "history",
	IotDevice:                 "iot_device",
	Organisation:              "organisation",
	OriginatorClass:           "originator_class",
	ParamRepr:                 "param_repr",
	ParamReprAssetTypeMapping: "param_repr_asset_type_mapping",
	ParamType:                 "param_type",
	Telemetry:                 "telemetry",
}
