// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// IotDevice is an object representing the database table.
type IotDevice struct {
	ID             int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	OrganisationID null.Int    `boil:"organisation_id" json:"organisation_id,omitempty" toml:"organisation_id" yaml:"organisation_id,omitempty"`
	Name           string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Type           null.String `boil:"type" json:"type,omitempty" toml:"type" yaml:"type,omitempty"`
	Meta           null.JSON   `boil:"meta" json:"meta,omitempty" toml:"meta" yaml:"meta,omitempty"`

	R *iotDeviceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L iotDeviceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IotDeviceColumns = struct {
	ID             string
	OrganisationID string
	Name           string
	Type           string
	Meta           string
}{
	ID:             "id",
	OrganisationID: "organisation_id",
	Name:           "name",
	Type:           "type",
	Meta:           "meta",
}

var IotDeviceTableColumns = struct {
	ID             string
	OrganisationID string
	Name           string
	Type           string
	Meta           string
}{
	ID:             "iot_device.id",
	OrganisationID: "iot_device.organisation_id",
	Name:           "iot_device.name",
	Type:           "iot_device.type",
	Meta:           "iot_device.meta",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var IotDeviceWhere = struct {
	ID             whereHelperint64
	OrganisationID whereHelpernull_Int
	Name           whereHelperstring
	Type           whereHelpernull_String
	Meta           whereHelpernull_JSON
}{
	ID:             whereHelperint64{field: "\"iot_device\".\"id\""},
	OrganisationID: whereHelpernull_Int{field: "\"iot_device\".\"organisation_id\""},
	Name:           whereHelperstring{field: "\"iot_device\".\"name\""},
	Type:           whereHelpernull_String{field: "\"iot_device\".\"type\""},
	Meta:           whereHelpernull_JSON{field: "\"iot_device\".\"meta\""},
}

// IotDeviceRels is where relationship names are stored.
var IotDeviceRels = struct {
	Organisation string
}{
	Organisation: "Organisation",
}

// iotDeviceR is where relationships are stored.
type iotDeviceR struct {
	Organisation *Organisation `boil:"Organisation" json:"Organisation" toml:"Organisation" yaml:"Organisation"`
}

// NewStruct creates a new relationship struct
func (*iotDeviceR) NewStruct() *iotDeviceR {
	return &iotDeviceR{}
}

func (o *IotDevice) GetOrganisation() *Organisation {
	if o == nil {
		return nil
	}

	return o.R.GetOrganisation()
}

func (r *iotDeviceR) GetOrganisation() *Organisation {
	if r == nil {
		return nil
	}

	return r.Organisation
}

// iotDeviceL is where Load methods for each relationship are stored.
type iotDeviceL struct{}

var (
	iotDeviceAllColumns            = []string{"id", "organisation_id", "name", "type", "meta"}
	iotDeviceColumnsWithoutDefault = []string{"name"}
	iotDeviceColumnsWithDefault    = []string{"id", "organisation_id", "type", "meta"}
	iotDevicePrimaryKeyColumns     = []string{"id"}
	iotDeviceGeneratedColumns      = []string{}
)

type (
	// IotDeviceSlice is an alias for a slice of pointers to IotDevice.
	// This should almost always be used instead of []IotDevice.
	IotDeviceSlice []*IotDevice
	// IotDeviceHook is the signature for custom IotDevice hook methods
	IotDeviceHook func(context.Context, boil.ContextExecutor, *IotDevice) error

	iotDeviceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	iotDeviceType                 = reflect.TypeOf(&IotDevice{})
	iotDeviceMapping              = queries.MakeStructMapping(iotDeviceType)
	iotDevicePrimaryKeyMapping, _ = queries.BindMapping(iotDeviceType, iotDeviceMapping, iotDevicePrimaryKeyColumns)
	iotDeviceInsertCacheMut       sync.RWMutex
	iotDeviceInsertCache          = make(map[string]insertCache)
	iotDeviceUpdateCacheMut       sync.RWMutex
	iotDeviceUpdateCache          = make(map[string]updateCache)
	iotDeviceUpsertCacheMut       sync.RWMutex
	iotDeviceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var iotDeviceAfterSelectMu sync.Mutex
var iotDeviceAfterSelectHooks []IotDeviceHook

var iotDeviceBeforeInsertMu sync.Mutex
var iotDeviceBeforeInsertHooks []IotDeviceHook
var iotDeviceAfterInsertMu sync.Mutex
var iotDeviceAfterInsertHooks []IotDeviceHook

var iotDeviceBeforeUpdateMu sync.Mutex
var iotDeviceBeforeUpdateHooks []IotDeviceHook
var iotDeviceAfterUpdateMu sync.Mutex
var iotDeviceAfterUpdateHooks []IotDeviceHook

var iotDeviceBeforeDeleteMu sync.Mutex
var iotDeviceBeforeDeleteHooks []IotDeviceHook
var iotDeviceAfterDeleteMu sync.Mutex
var iotDeviceAfterDeleteHooks []IotDeviceHook

var iotDeviceBeforeUpsertMu sync.Mutex
var iotDeviceBeforeUpsertHooks []IotDeviceHook
var iotDeviceAfterUpsertMu sync.Mutex
var iotDeviceAfterUpsertHooks []IotDeviceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IotDevice) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *IotDevice) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *IotDevice) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *IotDevice) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *IotDevice) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *IotDevice) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *IotDevice) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *IotDevice) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *IotDevice) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range iotDeviceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIotDeviceHook registers your hook function for all future operations.
func AddIotDeviceHook(hookPoint boil.HookPoint, iotDeviceHook IotDeviceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		iotDeviceAfterSelectMu.Lock()
		iotDeviceAfterSelectHooks = append(iotDeviceAfterSelectHooks, iotDeviceHook)
		iotDeviceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		iotDeviceBeforeInsertMu.Lock()
		iotDeviceBeforeInsertHooks = append(iotDeviceBeforeInsertHooks, iotDeviceHook)
		iotDeviceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		iotDeviceAfterInsertMu.Lock()
		iotDeviceAfterInsertHooks = append(iotDeviceAfterInsertHooks, iotDeviceHook)
		iotDeviceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		iotDeviceBeforeUpdateMu.Lock()
		iotDeviceBeforeUpdateHooks = append(iotDeviceBeforeUpdateHooks, iotDeviceHook)
		iotDeviceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		iotDeviceAfterUpdateMu.Lock()
		iotDeviceAfterUpdateHooks = append(iotDeviceAfterUpdateHooks, iotDeviceHook)
		iotDeviceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		iotDeviceBeforeDeleteMu.Lock()
		iotDeviceBeforeDeleteHooks = append(iotDeviceBeforeDeleteHooks, iotDeviceHook)
		iotDeviceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		iotDeviceAfterDeleteMu.Lock()
		iotDeviceAfterDeleteHooks = append(iotDeviceAfterDeleteHooks, iotDeviceHook)
		iotDeviceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		iotDeviceBeforeUpsertMu.Lock()
		iotDeviceBeforeUpsertHooks = append(iotDeviceBeforeUpsertHooks, iotDeviceHook)
		iotDeviceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		iotDeviceAfterUpsertMu.Lock()
		iotDeviceAfterUpsertHooks = append(iotDeviceAfterUpsertHooks, iotDeviceHook)
		iotDeviceAfterUpsertMu.Unlock()
	}
}

// OneG returns a single iotDevice record from the query using the global executor.
func (q iotDeviceQuery) OneG(ctx context.Context) (*IotDevice, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single iotDevice record from the query.
func (q iotDeviceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IotDevice, error) {
	o := &IotDevice{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for iot_device")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all IotDevice records from the query using the global executor.
func (q iotDeviceQuery) AllG(ctx context.Context) (IotDeviceSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all IotDevice records from the query.
func (q iotDeviceQuery) All(ctx context.Context, exec boil.ContextExecutor) (IotDeviceSlice, error) {
	var o []*IotDevice

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to IotDevice slice")
	}

	if len(iotDeviceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all IotDevice records in the query using the global executor
func (q iotDeviceQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all IotDevice records in the query.
func (q iotDeviceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count iot_device rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q iotDeviceQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q iotDeviceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if iot_device exists")
	}

	return count > 0, nil
}

// Organisation pointed to by the foreign key.
func (o *IotDevice) Organisation(mods ...qm.QueryMod) organisationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OrganisationID),
	}

	queryMods = append(queryMods, mods...)

	return Organisations(queryMods...)
}

// LoadOrganisation allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (iotDeviceL) LoadOrganisation(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIotDevice interface{}, mods queries.Applicator) error {
	var slice []*IotDevice
	var object *IotDevice

	if singular {
		var ok bool
		object, ok = maybeIotDevice.(*IotDevice)
		if !ok {
			object = new(IotDevice)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIotDevice)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIotDevice))
			}
		}
	} else {
		s, ok := maybeIotDevice.(*[]*IotDevice)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIotDevice)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIotDevice))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &iotDeviceR{}
		}
		if !queries.IsNil(object.OrganisationID) {
			args[object.OrganisationID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &iotDeviceR{}
			}

			if !queries.IsNil(obj.OrganisationID) {
				args[obj.OrganisationID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`organisation`),
		qm.WhereIn(`organisation.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Organisation")
	}

	var resultSlice []*Organisation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Organisation")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for organisation")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for organisation")
	}

	if len(organisationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Organisation = foreign
		if foreign.R == nil {
			foreign.R = &organisationR{}
		}
		foreign.R.IotDevices = append(foreign.R.IotDevices, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.OrganisationID, foreign.ID) {
				local.R.Organisation = foreign
				if foreign.R == nil {
					foreign.R = &organisationR{}
				}
				foreign.R.IotDevices = append(foreign.R.IotDevices, local)
				break
			}
		}
	}

	return nil
}

// SetOrganisationG of the iotDevice to the related item.
// Sets o.R.Organisation to related.
// Adds o to related.R.IotDevices.
// Uses the global database handle.
func (o *IotDevice) SetOrganisationG(ctx context.Context, insert bool, related *Organisation) error {
	return o.SetOrganisation(ctx, boil.GetContextDB(), insert, related)
}

// SetOrganisation of the iotDevice to the related item.
// Sets o.R.Organisation to related.
// Adds o to related.R.IotDevices.
func (o *IotDevice) SetOrganisation(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Organisation) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"iot_device\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"organisation_id"}),
		strmangle.WhereClause("\"", "\"", 2, iotDevicePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.OrganisationID, related.ID)
	if o.R == nil {
		o.R = &iotDeviceR{
			Organisation: related,
		}
	} else {
		o.R.Organisation = related
	}

	if related.R == nil {
		related.R = &organisationR{
			IotDevices: IotDeviceSlice{o},
		}
	} else {
		related.R.IotDevices = append(related.R.IotDevices, o)
	}

	return nil
}

// RemoveOrganisationG relationship.
// Sets o.R.Organisation to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *IotDevice) RemoveOrganisationG(ctx context.Context, related *Organisation) error {
	return o.RemoveOrganisation(ctx, boil.GetContextDB(), related)
}

// RemoveOrganisation relationship.
// Sets o.R.Organisation to nil.
// Removes o from all passed in related items' relationships struct.
func (o *IotDevice) RemoveOrganisation(ctx context.Context, exec boil.ContextExecutor, related *Organisation) error {
	var err error

	queries.SetScanner(&o.OrganisationID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("organisation_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Organisation = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.IotDevices {
		if queries.Equal(o.OrganisationID, ri.OrganisationID) {
			continue
		}

		ln := len(related.R.IotDevices)
		if ln > 1 && i < ln-1 {
			related.R.IotDevices[i] = related.R.IotDevices[ln-1]
		}
		related.R.IotDevices = related.R.IotDevices[:ln-1]
		break
	}
	return nil
}

// IotDevices retrieves all the records using an executor.
func IotDevices(mods ...qm.QueryMod) iotDeviceQuery {
	mods = append(mods, qm.From("\"iot_device\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"iot_device\".*"})
	}

	return iotDeviceQuery{q}
}

// FindIotDeviceG retrieves a single record by ID.
func FindIotDeviceG(ctx context.Context, iD int64, selectCols ...string) (*IotDevice, error) {
	return FindIotDevice(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindIotDevice retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIotDevice(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*IotDevice, error) {
	iotDeviceObj := &IotDevice{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"iot_device\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, iotDeviceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from iot_device")
	}

	if err = iotDeviceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return iotDeviceObj, err
	}

	return iotDeviceObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *IotDevice) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IotDevice) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no iot_device provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(iotDeviceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	iotDeviceInsertCacheMut.RLock()
	cache, cached := iotDeviceInsertCache[key]
	iotDeviceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			iotDeviceAllColumns,
			iotDeviceColumnsWithDefault,
			iotDeviceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(iotDeviceType, iotDeviceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(iotDeviceType, iotDeviceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"iot_device\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"iot_device\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into iot_device")
	}

	if !cached {
		iotDeviceInsertCacheMut.Lock()
		iotDeviceInsertCache[key] = cache
		iotDeviceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single IotDevice record using the global executor.
// See Update for more documentation.
func (o *IotDevice) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the IotDevice.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IotDevice) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	iotDeviceUpdateCacheMut.RLock()
	cache, cached := iotDeviceUpdateCache[key]
	iotDeviceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			iotDeviceAllColumns,
			iotDevicePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update iot_device, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"iot_device\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, iotDevicePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(iotDeviceType, iotDeviceMapping, append(wl, iotDevicePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update iot_device row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for iot_device")
	}

	if !cached {
		iotDeviceUpdateCacheMut.Lock()
		iotDeviceUpdateCache[key] = cache
		iotDeviceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q iotDeviceQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q iotDeviceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for iot_device")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for iot_device")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o IotDeviceSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IotDeviceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), iotDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"iot_device\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, iotDevicePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in iotDevice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all iotDevice")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *IotDevice) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IotDevice) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no iot_device provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(iotDeviceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	iotDeviceUpsertCacheMut.RLock()
	cache, cached := iotDeviceUpsertCache[key]
	iotDeviceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			iotDeviceAllColumns,
			iotDeviceColumnsWithDefault,
			iotDeviceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			iotDeviceAllColumns,
			iotDevicePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert iot_device, could not build update column list")
		}

		ret := strmangle.SetComplement(iotDeviceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(iotDevicePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert iot_device, could not build conflict column list")
			}

			conflict = make([]string, len(iotDevicePrimaryKeyColumns))
			copy(conflict, iotDevicePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"iot_device\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(iotDeviceType, iotDeviceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(iotDeviceType, iotDeviceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert iot_device")
	}

	if !cached {
		iotDeviceUpsertCacheMut.Lock()
		iotDeviceUpsertCache[key] = cache
		iotDeviceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single IotDevice record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *IotDevice) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single IotDevice record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IotDevice) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no IotDevice provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), iotDevicePrimaryKeyMapping)
	sql := "DELETE FROM \"iot_device\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from iot_device")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for iot_device")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q iotDeviceQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q iotDeviceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no iotDeviceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from iot_device")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for iot_device")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o IotDeviceSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IotDeviceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(iotDeviceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), iotDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"iot_device\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, iotDevicePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from iotDevice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for iot_device")
	}

	if len(iotDeviceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *IotDevice) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no IotDevice provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IotDevice) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIotDevice(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IotDeviceSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty IotDeviceSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IotDeviceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IotDeviceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), iotDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"iot_device\".* FROM \"iot_device\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, iotDevicePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in IotDeviceSlice")
	}

	*o = slice

	return nil
}

// IotDeviceExistsG checks if the IotDevice row exists.
func IotDeviceExistsG(ctx context.Context, iD int64) (bool, error) {
	return IotDeviceExists(ctx, boil.GetContextDB(), iD)
}

// IotDeviceExists checks if the IotDevice row exists.
func IotDeviceExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"iot_device\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if iot_device exists")
	}

	return exists, nil
}

// Exists checks if the IotDevice row exists.
func (o *IotDevice) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return IotDeviceExists(ctx, exec, o.ID)
}
