// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Organisation is an object representing the database table.
type Organisation struct {
	ID       int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Class    string      `boil:"class" json:"class" toml:"class" yaml:"class"`
	Code     string      `boil:"code" json:"code" toml:"code" yaml:"code"`
	Alias    null.String `boil:"alias" json:"alias,omitempty" toml:"alias" yaml:"alias,omitempty"`
	HexCode  string      `boil:"hex_code" json:"hex_code" toml:"hex_code" yaml:"hex_code"`
	ParentID null.Int    `boil:"parent_id" json:"parent_id,omitempty" toml:"parent_id" yaml:"parent_id,omitempty"`

	R *organisationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L organisationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OrganisationColumns = struct {
	ID       string
	Class    string
	Code     string
	Alias    string
	HexCode  string
	ParentID string
}{
	ID:       "id",
	Class:    "class",
	Code:     "code",
	Alias:    "alias",
	HexCode:  "hex_code",
	ParentID: "parent_id",
}

var OrganisationTableColumns = struct {
	ID       string
	Class    string
	Code     string
	Alias    string
	HexCode  string
	ParentID string
}{
	ID:       "organisation.id",
	Class:    "organisation.class",
	Code:     "organisation.code",
	Alias:    "organisation.alias",
	HexCode:  "organisation.hex_code",
	ParentID: "organisation.parent_id",
}

// Generated where

var OrganisationWhere = struct {
	ID       whereHelperint
	Class    whereHelperstring
	Code     whereHelperstring
	Alias    whereHelpernull_String
	HexCode  whereHelperstring
	ParentID whereHelpernull_Int
}{
	ID:       whereHelperint{field: "\"organisation\".\"id\""},
	Class:    whereHelperstring{field: "\"organisation\".\"class\""},
	Code:     whereHelperstring{field: "\"organisation\".\"code\""},
	Alias:    whereHelpernull_String{field: "\"organisation\".\"alias\""},
	HexCode:  whereHelperstring{field: "\"organisation\".\"hex_code\""},
	ParentID: whereHelpernull_Int{field: "\"organisation\".\"parent_id\""},
}

// OrganisationRels is where relationship names are stored.
var OrganisationRels = struct {
	Parent              string
	Assets              string
	EdgeGateways        string
	IotDevices          string
	ParentOrganisations string
}{
	Parent:              "Parent",
	Assets:              "Assets",
	EdgeGateways:        "EdgeGateways",
	IotDevices:          "IotDevices",
	ParentOrganisations: "ParentOrganisations",
}

// organisationR is where relationships are stored.
type organisationR struct {
	Parent              *Organisation     `boil:"Parent" json:"Parent" toml:"Parent" yaml:"Parent"`
	Assets              AssetSlice        `boil:"Assets" json:"Assets" toml:"Assets" yaml:"Assets"`
	EdgeGateways        EdgeGatewaySlice  `boil:"EdgeGateways" json:"EdgeGateways" toml:"EdgeGateways" yaml:"EdgeGateways"`
	IotDevices          IotDeviceSlice    `boil:"IotDevices" json:"IotDevices" toml:"IotDevices" yaml:"IotDevices"`
	ParentOrganisations OrganisationSlice `boil:"ParentOrganisations" json:"ParentOrganisations" toml:"ParentOrganisations" yaml:"ParentOrganisations"`
}

// NewStruct creates a new relationship struct
func (*organisationR) NewStruct() *organisationR {
	return &organisationR{}
}

func (o *Organisation) GetParent() *Organisation {
	if o == nil {
		return nil
	}

	return o.R.GetParent()
}

func (r *organisationR) GetParent() *Organisation {
	if r == nil {
		return nil
	}

	return r.Parent
}

func (o *Organisation) GetAssets() AssetSlice {
	if o == nil {
		return nil
	}

	return o.R.GetAssets()
}

func (r *organisationR) GetAssets() AssetSlice {
	if r == nil {
		return nil
	}

	return r.Assets
}

func (o *Organisation) GetEdgeGateways() EdgeGatewaySlice {
	if o == nil {
		return nil
	}

	return o.R.GetEdgeGateways()
}

func (r *organisationR) GetEdgeGateways() EdgeGatewaySlice {
	if r == nil {
		return nil
	}

	return r.EdgeGateways
}

func (o *Organisation) GetIotDevices() IotDeviceSlice {
	if o == nil {
		return nil
	}

	return o.R.GetIotDevices()
}

func (r *organisationR) GetIotDevices() IotDeviceSlice {
	if r == nil {
		return nil
	}

	return r.IotDevices
}

func (o *Organisation) GetParentOrganisations() OrganisationSlice {
	if o == nil {
		return nil
	}

	return o.R.GetParentOrganisations()
}

func (r *organisationR) GetParentOrganisations() OrganisationSlice {
	if r == nil {
		return nil
	}

	return r.ParentOrganisations
}

// organisationL is where Load methods for each relationship are stored.
type organisationL struct{}

var (
	organisationAllColumns            = []string{"id", "class", "code", "alias", "hex_code", "parent_id"}
	organisationColumnsWithoutDefault = []string{"class", "code", "hex_code"}
	organisationColumnsWithDefault    = []string{"id", "alias", "parent_id"}
	organisationPrimaryKeyColumns     = []string{"id"}
	organisationGeneratedColumns      = []string{}
)

type (
	// OrganisationSlice is an alias for a slice of pointers to Organisation.
	// This should almost always be used instead of []Organisation.
	OrganisationSlice []*Organisation
	// OrganisationHook is the signature for custom Organisation hook methods
	OrganisationHook func(context.Context, boil.ContextExecutor, *Organisation) error

	organisationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	organisationType                 = reflect.TypeOf(&Organisation{})
	organisationMapping              = queries.MakeStructMapping(organisationType)
	organisationPrimaryKeyMapping, _ = queries.BindMapping(organisationType, organisationMapping, organisationPrimaryKeyColumns)
	organisationInsertCacheMut       sync.RWMutex
	organisationInsertCache          = make(map[string]insertCache)
	organisationUpdateCacheMut       sync.RWMutex
	organisationUpdateCache          = make(map[string]updateCache)
	organisationUpsertCacheMut       sync.RWMutex
	organisationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var organisationAfterSelectMu sync.Mutex
var organisationAfterSelectHooks []OrganisationHook

var organisationBeforeInsertMu sync.Mutex
var organisationBeforeInsertHooks []OrganisationHook
var organisationAfterInsertMu sync.Mutex
var organisationAfterInsertHooks []OrganisationHook

var organisationBeforeUpdateMu sync.Mutex
var organisationBeforeUpdateHooks []OrganisationHook
var organisationAfterUpdateMu sync.Mutex
var organisationAfterUpdateHooks []OrganisationHook

var organisationBeforeDeleteMu sync.Mutex
var organisationBeforeDeleteHooks []OrganisationHook
var organisationAfterDeleteMu sync.Mutex
var organisationAfterDeleteHooks []OrganisationHook

var organisationBeforeUpsertMu sync.Mutex
var organisationBeforeUpsertHooks []OrganisationHook
var organisationAfterUpsertMu sync.Mutex
var organisationAfterUpsertHooks []OrganisationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Organisation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Organisation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Organisation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Organisation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Organisation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Organisation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Organisation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Organisation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Organisation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range organisationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOrganisationHook registers your hook function for all future operations.
func AddOrganisationHook(hookPoint boil.HookPoint, organisationHook OrganisationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		organisationAfterSelectMu.Lock()
		organisationAfterSelectHooks = append(organisationAfterSelectHooks, organisationHook)
		organisationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		organisationBeforeInsertMu.Lock()
		organisationBeforeInsertHooks = append(organisationBeforeInsertHooks, organisationHook)
		organisationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		organisationAfterInsertMu.Lock()
		organisationAfterInsertHooks = append(organisationAfterInsertHooks, organisationHook)
		organisationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		organisationBeforeUpdateMu.Lock()
		organisationBeforeUpdateHooks = append(organisationBeforeUpdateHooks, organisationHook)
		organisationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		organisationAfterUpdateMu.Lock()
		organisationAfterUpdateHooks = append(organisationAfterUpdateHooks, organisationHook)
		organisationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		organisationBeforeDeleteMu.Lock()
		organisationBeforeDeleteHooks = append(organisationBeforeDeleteHooks, organisationHook)
		organisationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		organisationAfterDeleteMu.Lock()
		organisationAfterDeleteHooks = append(organisationAfterDeleteHooks, organisationHook)
		organisationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		organisationBeforeUpsertMu.Lock()
		organisationBeforeUpsertHooks = append(organisationBeforeUpsertHooks, organisationHook)
		organisationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		organisationAfterUpsertMu.Lock()
		organisationAfterUpsertHooks = append(organisationAfterUpsertHooks, organisationHook)
		organisationAfterUpsertMu.Unlock()
	}
}

// OneG returns a single organisation record from the query using the global executor.
func (q organisationQuery) OneG(ctx context.Context) (*Organisation, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single organisation record from the query.
func (q organisationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Organisation, error) {
	o := &Organisation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for organisation")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Organisation records from the query using the global executor.
func (q organisationQuery) AllG(ctx context.Context) (OrganisationSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Organisation records from the query.
func (q organisationQuery) All(ctx context.Context, exec boil.ContextExecutor) (OrganisationSlice, error) {
	var o []*Organisation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Organisation slice")
	}

	if len(organisationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Organisation records in the query using the global executor
func (q organisationQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Organisation records in the query.
func (q organisationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count organisation rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q organisationQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q organisationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if organisation exists")
	}

	return count > 0, nil
}

// Parent pointed to by the foreign key.
func (o *Organisation) Parent(mods ...qm.QueryMod) organisationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ParentID),
	}

	queryMods = append(queryMods, mods...)

	return Organisations(queryMods...)
}

// Assets retrieves all the asset's Assets with an executor.
func (o *Organisation) Assets(mods ...qm.QueryMod) assetQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"asset\".\"organisation_id\"=?", o.ID),
	)

	return Assets(queryMods...)
}

// EdgeGateways retrieves all the edge_gateway's EdgeGateways with an executor.
func (o *Organisation) EdgeGateways(mods ...qm.QueryMod) edgeGatewayQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"edge_gateway\".\"organisation_id\"=?", o.ID),
	)

	return EdgeGateways(queryMods...)
}

// IotDevices retrieves all the iot_device's IotDevices with an executor.
func (o *Organisation) IotDevices(mods ...qm.QueryMod) iotDeviceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"iot_device\".\"organisation_id\"=?", o.ID),
	)

	return IotDevices(queryMods...)
}

// ParentOrganisations retrieves all the organisation's Organisations with an executor via parent_id column.
func (o *Organisation) ParentOrganisations(mods ...qm.QueryMod) organisationQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"organisation\".\"parent_id\"=?", o.ID),
	)

	return Organisations(queryMods...)
}

// LoadParent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (organisationL) LoadParent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganisation interface{}, mods queries.Applicator) error {
	var slice []*Organisation
	var object *Organisation

	if singular {
		var ok bool
		object, ok = maybeOrganisation.(*Organisation)
		if !ok {
			object = new(Organisation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrganisation))
			}
		}
	} else {
		s, ok := maybeOrganisation.(*[]*Organisation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrganisation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &organisationR{}
		}
		if !queries.IsNil(object.ParentID) {
			args[object.ParentID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organisationR{}
			}

			if !queries.IsNil(obj.ParentID) {
				args[obj.ParentID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`organisation`),
		qm.WhereIn(`organisation.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Organisation")
	}

	var resultSlice []*Organisation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Organisation")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for organisation")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for organisation")
	}

	if len(organisationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Parent = foreign
		if foreign.R == nil {
			foreign.R = &organisationR{}
		}
		foreign.R.ParentOrganisations = append(foreign.R.ParentOrganisations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ParentID, foreign.ID) {
				local.R.Parent = foreign
				if foreign.R == nil {
					foreign.R = &organisationR{}
				}
				foreign.R.ParentOrganisations = append(foreign.R.ParentOrganisations, local)
				break
			}
		}
	}

	return nil
}

// LoadAssets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (organisationL) LoadAssets(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganisation interface{}, mods queries.Applicator) error {
	var slice []*Organisation
	var object *Organisation

	if singular {
		var ok bool
		object, ok = maybeOrganisation.(*Organisation)
		if !ok {
			object = new(Organisation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrganisation))
			}
		}
	} else {
		s, ok := maybeOrganisation.(*[]*Organisation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrganisation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &organisationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organisationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`asset`),
		qm.WhereIn(`asset.organisation_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load asset")
	}

	var resultSlice []*Asset
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice asset")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on asset")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for asset")
	}

	if len(assetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Assets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &assetR{}
			}
			foreign.R.Organisation = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OrganisationID {
				local.R.Assets = append(local.R.Assets, foreign)
				if foreign.R == nil {
					foreign.R = &assetR{}
				}
				foreign.R.Organisation = local
				break
			}
		}
	}

	return nil
}

// LoadEdgeGateways allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (organisationL) LoadEdgeGateways(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganisation interface{}, mods queries.Applicator) error {
	var slice []*Organisation
	var object *Organisation

	if singular {
		var ok bool
		object, ok = maybeOrganisation.(*Organisation)
		if !ok {
			object = new(Organisation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrganisation))
			}
		}
	} else {
		s, ok := maybeOrganisation.(*[]*Organisation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrganisation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &organisationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organisationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`edge_gateway`),
		qm.WhereIn(`edge_gateway.organisation_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load edge_gateway")
	}

	var resultSlice []*EdgeGateway
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice edge_gateway")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on edge_gateway")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for edge_gateway")
	}

	if len(edgeGatewayAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.EdgeGateways = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &edgeGatewayR{}
			}
			foreign.R.Organisation = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OrganisationID {
				local.R.EdgeGateways = append(local.R.EdgeGateways, foreign)
				if foreign.R == nil {
					foreign.R = &edgeGatewayR{}
				}
				foreign.R.Organisation = local
				break
			}
		}
	}

	return nil
}

// LoadIotDevices allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (organisationL) LoadIotDevices(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganisation interface{}, mods queries.Applicator) error {
	var slice []*Organisation
	var object *Organisation

	if singular {
		var ok bool
		object, ok = maybeOrganisation.(*Organisation)
		if !ok {
			object = new(Organisation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrganisation))
			}
		}
	} else {
		s, ok := maybeOrganisation.(*[]*Organisation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrganisation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &organisationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organisationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`iot_device`),
		qm.WhereIn(`iot_device.organisation_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load iot_device")
	}

	var resultSlice []*IotDevice
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice iot_device")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on iot_device")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for iot_device")
	}

	if len(iotDeviceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.IotDevices = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &iotDeviceR{}
			}
			foreign.R.Organisation = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.OrganisationID) {
				local.R.IotDevices = append(local.R.IotDevices, foreign)
				if foreign.R == nil {
					foreign.R = &iotDeviceR{}
				}
				foreign.R.Organisation = local
				break
			}
		}
	}

	return nil
}

// LoadParentOrganisations allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (organisationL) LoadParentOrganisations(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOrganisation interface{}, mods queries.Applicator) error {
	var slice []*Organisation
	var object *Organisation

	if singular {
		var ok bool
		object, ok = maybeOrganisation.(*Organisation)
		if !ok {
			object = new(Organisation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOrganisation))
			}
		}
	} else {
		s, ok := maybeOrganisation.(*[]*Organisation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOrganisation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOrganisation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &organisationR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &organisationR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`organisation`),
		qm.WhereIn(`organisation.parent_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load organisation")
	}

	var resultSlice []*Organisation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice organisation")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on organisation")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for organisation")
	}

	if len(organisationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ParentOrganisations = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &organisationR{}
			}
			foreign.R.Parent = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ParentID) {
				local.R.ParentOrganisations = append(local.R.ParentOrganisations, foreign)
				if foreign.R == nil {
					foreign.R = &organisationR{}
				}
				foreign.R.Parent = local
				break
			}
		}
	}

	return nil
}

// SetParentG of the organisation to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentOrganisations.
// Uses the global database handle.
func (o *Organisation) SetParentG(ctx context.Context, insert bool, related *Organisation) error {
	return o.SetParent(ctx, boil.GetContextDB(), insert, related)
}

// SetParent of the organisation to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentOrganisations.
func (o *Organisation) SetParent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Organisation) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"organisation\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
		strmangle.WhereClause("\"", "\"", 2, organisationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ParentID, related.ID)
	if o.R == nil {
		o.R = &organisationR{
			Parent: related,
		}
	} else {
		o.R.Parent = related
	}

	if related.R == nil {
		related.R = &organisationR{
			ParentOrganisations: OrganisationSlice{o},
		}
	} else {
		related.R.ParentOrganisations = append(related.R.ParentOrganisations, o)
	}

	return nil
}

// RemoveParentG relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *Organisation) RemoveParentG(ctx context.Context, related *Organisation) error {
	return o.RemoveParent(ctx, boil.GetContextDB(), related)
}

// RemoveParent relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Organisation) RemoveParent(ctx context.Context, exec boil.ContextExecutor, related *Organisation) error {
	var err error

	queries.SetScanner(&o.ParentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("parent_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Parent = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ParentOrganisations {
		if queries.Equal(o.ParentID, ri.ParentID) {
			continue
		}

		ln := len(related.R.ParentOrganisations)
		if ln > 1 && i < ln-1 {
			related.R.ParentOrganisations[i] = related.R.ParentOrganisations[ln-1]
		}
		related.R.ParentOrganisations = related.R.ParentOrganisations[:ln-1]
		break
	}
	return nil
}

// AddAssetsG adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.Assets.
// Sets related.R.Organisation appropriately.
// Uses the global database handle.
func (o *Organisation) AddAssetsG(ctx context.Context, insert bool, related ...*Asset) error {
	return o.AddAssets(ctx, boil.GetContextDB(), insert, related...)
}

// AddAssets adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.Assets.
// Sets related.R.Organisation appropriately.
func (o *Organisation) AddAssets(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Asset) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OrganisationID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"asset\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"organisation_id"}),
				strmangle.WhereClause("\"", "\"", 2, assetPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OrganisationID = o.ID
		}
	}

	if o.R == nil {
		o.R = &organisationR{
			Assets: related,
		}
	} else {
		o.R.Assets = append(o.R.Assets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &assetR{
				Organisation: o,
			}
		} else {
			rel.R.Organisation = o
		}
	}
	return nil
}

// AddEdgeGatewaysG adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.EdgeGateways.
// Sets related.R.Organisation appropriately.
// Uses the global database handle.
func (o *Organisation) AddEdgeGatewaysG(ctx context.Context, insert bool, related ...*EdgeGateway) error {
	return o.AddEdgeGateways(ctx, boil.GetContextDB(), insert, related...)
}

// AddEdgeGateways adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.EdgeGateways.
// Sets related.R.Organisation appropriately.
func (o *Organisation) AddEdgeGateways(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*EdgeGateway) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OrganisationID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"edge_gateway\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"organisation_id"}),
				strmangle.WhereClause("\"", "\"", 2, edgeGatewayPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OrganisationID = o.ID
		}
	}

	if o.R == nil {
		o.R = &organisationR{
			EdgeGateways: related,
		}
	} else {
		o.R.EdgeGateways = append(o.R.EdgeGateways, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &edgeGatewayR{
				Organisation: o,
			}
		} else {
			rel.R.Organisation = o
		}
	}
	return nil
}

// AddIotDevicesG adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.IotDevices.
// Sets related.R.Organisation appropriately.
// Uses the global database handle.
func (o *Organisation) AddIotDevicesG(ctx context.Context, insert bool, related ...*IotDevice) error {
	return o.AddIotDevices(ctx, boil.GetContextDB(), insert, related...)
}

// AddIotDevices adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.IotDevices.
// Sets related.R.Organisation appropriately.
func (o *Organisation) AddIotDevices(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IotDevice) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.OrganisationID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"iot_device\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"organisation_id"}),
				strmangle.WhereClause("\"", "\"", 2, iotDevicePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.OrganisationID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &organisationR{
			IotDevices: related,
		}
	} else {
		o.R.IotDevices = append(o.R.IotDevices, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &iotDeviceR{
				Organisation: o,
			}
		} else {
			rel.R.Organisation = o
		}
	}
	return nil
}

// SetIotDevicesG removes all previously related items of the
// organisation replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Organisation's IotDevices accordingly.
// Replaces o.R.IotDevices with related.
// Sets related.R.Organisation's IotDevices accordingly.
// Uses the global database handle.
func (o *Organisation) SetIotDevicesG(ctx context.Context, insert bool, related ...*IotDevice) error {
	return o.SetIotDevices(ctx, boil.GetContextDB(), insert, related...)
}

// SetIotDevices removes all previously related items of the
// organisation replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Organisation's IotDevices accordingly.
// Replaces o.R.IotDevices with related.
// Sets related.R.Organisation's IotDevices accordingly.
func (o *Organisation) SetIotDevices(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*IotDevice) error {
	query := "update \"iot_device\" set \"organisation_id\" = null where \"organisation_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.IotDevices {
			queries.SetScanner(&rel.OrganisationID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Organisation = nil
		}
		o.R.IotDevices = nil
	}

	return o.AddIotDevices(ctx, exec, insert, related...)
}

// RemoveIotDevicesG relationships from objects passed in.
// Removes related items from R.IotDevices (uses pointer comparison, removal does not keep order)
// Sets related.R.Organisation.
// Uses the global database handle.
func (o *Organisation) RemoveIotDevicesG(ctx context.Context, related ...*IotDevice) error {
	return o.RemoveIotDevices(ctx, boil.GetContextDB(), related...)
}

// RemoveIotDevices relationships from objects passed in.
// Removes related items from R.IotDevices (uses pointer comparison, removal does not keep order)
// Sets related.R.Organisation.
func (o *Organisation) RemoveIotDevices(ctx context.Context, exec boil.ContextExecutor, related ...*IotDevice) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.OrganisationID, nil)
		if rel.R != nil {
			rel.R.Organisation = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("organisation_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.IotDevices {
			if rel != ri {
				continue
			}

			ln := len(o.R.IotDevices)
			if ln > 1 && i < ln-1 {
				o.R.IotDevices[i] = o.R.IotDevices[ln-1]
			}
			o.R.IotDevices = o.R.IotDevices[:ln-1]
			break
		}
	}

	return nil
}

// AddParentOrganisationsG adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.ParentOrganisations.
// Sets related.R.Parent appropriately.
// Uses the global database handle.
func (o *Organisation) AddParentOrganisationsG(ctx context.Context, insert bool, related ...*Organisation) error {
	return o.AddParentOrganisations(ctx, boil.GetContextDB(), insert, related...)
}

// AddParentOrganisations adds the given related objects to the existing relationships
// of the organisation, optionally inserting them as new records.
// Appends related to o.R.ParentOrganisations.
// Sets related.R.Parent appropriately.
func (o *Organisation) AddParentOrganisations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Organisation) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ParentID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"organisation\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
				strmangle.WhereClause("\"", "\"", 2, organisationPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ParentID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &organisationR{
			ParentOrganisations: related,
		}
	} else {
		o.R.ParentOrganisations = append(o.R.ParentOrganisations, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &organisationR{
				Parent: o,
			}
		} else {
			rel.R.Parent = o
		}
	}
	return nil
}

// SetParentOrganisationsG removes all previously related items of the
// organisation replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentOrganisations accordingly.
// Replaces o.R.ParentOrganisations with related.
// Sets related.R.Parent's ParentOrganisations accordingly.
// Uses the global database handle.
func (o *Organisation) SetParentOrganisationsG(ctx context.Context, insert bool, related ...*Organisation) error {
	return o.SetParentOrganisations(ctx, boil.GetContextDB(), insert, related...)
}

// SetParentOrganisations removes all previously related items of the
// organisation replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentOrganisations accordingly.
// Replaces o.R.ParentOrganisations with related.
// Sets related.R.Parent's ParentOrganisations accordingly.
func (o *Organisation) SetParentOrganisations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Organisation) error {
	query := "update \"organisation\" set \"parent_id\" = null where \"parent_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ParentOrganisations {
			queries.SetScanner(&rel.ParentID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Parent = nil
		}
		o.R.ParentOrganisations = nil
	}

	return o.AddParentOrganisations(ctx, exec, insert, related...)
}

// RemoveParentOrganisationsG relationships from objects passed in.
// Removes related items from R.ParentOrganisations (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
// Uses the global database handle.
func (o *Organisation) RemoveParentOrganisationsG(ctx context.Context, related ...*Organisation) error {
	return o.RemoveParentOrganisations(ctx, boil.GetContextDB(), related...)
}

// RemoveParentOrganisations relationships from objects passed in.
// Removes related items from R.ParentOrganisations (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
func (o *Organisation) RemoveParentOrganisations(ctx context.Context, exec boil.ContextExecutor, related ...*Organisation) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ParentID, nil)
		if rel.R != nil {
			rel.R.Parent = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("parent_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ParentOrganisations {
			if rel != ri {
				continue
			}

			ln := len(o.R.ParentOrganisations)
			if ln > 1 && i < ln-1 {
				o.R.ParentOrganisations[i] = o.R.ParentOrganisations[ln-1]
			}
			o.R.ParentOrganisations = o.R.ParentOrganisations[:ln-1]
			break
		}
	}

	return nil
}

// Organisations retrieves all the records using an executor.
func Organisations(mods ...qm.QueryMod) organisationQuery {
	mods = append(mods, qm.From("\"organisation\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"organisation\".*"})
	}

	return organisationQuery{q}
}

// FindOrganisationG retrieves a single record by ID.
func FindOrganisationG(ctx context.Context, iD int, selectCols ...string) (*Organisation, error) {
	return FindOrganisation(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindOrganisation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOrganisation(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Organisation, error) {
	organisationObj := &Organisation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"organisation\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, organisationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from organisation")
	}

	if err = organisationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return organisationObj, err
	}

	return organisationObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Organisation) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Organisation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no organisation provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(organisationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	organisationInsertCacheMut.RLock()
	cache, cached := organisationInsertCache[key]
	organisationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			organisationAllColumns,
			organisationColumnsWithDefault,
			organisationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(organisationType, organisationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(organisationType, organisationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"organisation\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"organisation\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into organisation")
	}

	if !cached {
		organisationInsertCacheMut.Lock()
		organisationInsertCache[key] = cache
		organisationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Organisation record using the global executor.
// See Update for more documentation.
func (o *Organisation) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Organisation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Organisation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	organisationUpdateCacheMut.RLock()
	cache, cached := organisationUpdateCache[key]
	organisationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			organisationAllColumns,
			organisationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update organisation, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"organisation\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, organisationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(organisationType, organisationMapping, append(wl, organisationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update organisation row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for organisation")
	}

	if !cached {
		organisationUpdateCacheMut.Lock()
		organisationUpdateCache[key] = cache
		organisationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q organisationQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q organisationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for organisation")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for organisation")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o OrganisationSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OrganisationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organisationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"organisation\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, organisationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in organisation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all organisation")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Organisation) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Organisation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no organisation provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(organisationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	organisationUpsertCacheMut.RLock()
	cache, cached := organisationUpsertCache[key]
	organisationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			organisationAllColumns,
			organisationColumnsWithDefault,
			organisationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			organisationAllColumns,
			organisationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert organisation, could not build update column list")
		}

		ret := strmangle.SetComplement(organisationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(organisationPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert organisation, could not build conflict column list")
			}

			conflict = make([]string, len(organisationPrimaryKeyColumns))
			copy(conflict, organisationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"organisation\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(organisationType, organisationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(organisationType, organisationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert organisation")
	}

	if !cached {
		organisationUpsertCacheMut.Lock()
		organisationUpsertCache[key] = cache
		organisationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Organisation record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Organisation) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Organisation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Organisation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Organisation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), organisationPrimaryKeyMapping)
	sql := "DELETE FROM \"organisation\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from organisation")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for organisation")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q organisationQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q organisationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no organisationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from organisation")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for organisation")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o OrganisationSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OrganisationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(organisationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organisationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"organisation\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, organisationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from organisation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for organisation")
	}

	if len(organisationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Organisation) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Organisation provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Organisation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOrganisation(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OrganisationSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty OrganisationSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OrganisationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OrganisationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), organisationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"organisation\".* FROM \"organisation\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, organisationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OrganisationSlice")
	}

	*o = slice

	return nil
}

// OrganisationExistsG checks if the Organisation row exists.
func OrganisationExistsG(ctx context.Context, iD int) (bool, error) {
	return OrganisationExists(ctx, boil.GetContextDB(), iD)
}

// OrganisationExists checks if the Organisation row exists.
func OrganisationExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"organisation\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if organisation exists")
	}

	return exists, nil
}

// Exists checks if the Organisation row exists.
func (o *Organisation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OrganisationExists(ctx, exec, o.ID)
}
