// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// OriginatorClass is an object representing the database table.
type OriginatorClass struct {
	ID          int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	AssetTypeID int         `boil:"asset_type_id" json:"asset_type_id" toml:"asset_type_id" yaml:"asset_type_id"`
	Code        string      `boil:"code" json:"code" toml:"code" yaml:"code"`
	Alias       null.String `boil:"alias" json:"alias,omitempty" toml:"alias" yaml:"alias,omitempty"`

	R *originatorClassR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L originatorClassL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OriginatorClassColumns = struct {
	ID          string
	AssetTypeID string
	Code        string
	Alias       string
}{
	ID:          "id",
	AssetTypeID: "asset_type_id",
	Code:        "code",
	Alias:       "alias",
}

var OriginatorClassTableColumns = struct {
	ID          string
	AssetTypeID string
	Code        string
	Alias       string
}{
	ID:          "originator_class.id",
	AssetTypeID: "originator_class.asset_type_id",
	Code:        "originator_class.code",
	Alias:       "originator_class.alias",
}

// Generated where

var OriginatorClassWhere = struct {
	ID          whereHelperint
	AssetTypeID whereHelperint
	Code        whereHelperstring
	Alias       whereHelpernull_String
}{
	ID:          whereHelperint{field: "\"originator_class\".\"id\""},
	AssetTypeID: whereHelperint{field: "\"originator_class\".\"asset_type_id\""},
	Code:        whereHelperstring{field: "\"originator_class\".\"code\""},
	Alias:       whereHelpernull_String{field: "\"originator_class\".\"alias\""},
}

// OriginatorClassRels is where relationship names are stored.
var OriginatorClassRels = struct {
	AssetType                  string
	ParamReprAssetTypeMappings string
	Telemetries                string
}{
	AssetType:                  "AssetType",
	ParamReprAssetTypeMappings: "ParamReprAssetTypeMappings",
	Telemetries:                "Telemetries",
}

// originatorClassR is where relationships are stored.
type originatorClassR struct {
	AssetType                  *AssetType                     `boil:"AssetType" json:"AssetType" toml:"AssetType" yaml:"AssetType"`
	ParamReprAssetTypeMappings ParamReprAssetTypeMappingSlice `boil:"ParamReprAssetTypeMappings" json:"ParamReprAssetTypeMappings" toml:"ParamReprAssetTypeMappings" yaml:"ParamReprAssetTypeMappings"`
	Telemetries                TelemetrySlice                 `boil:"Telemetries" json:"Telemetries" toml:"Telemetries" yaml:"Telemetries"`
}

// NewStruct creates a new relationship struct
func (*originatorClassR) NewStruct() *originatorClassR {
	return &originatorClassR{}
}

func (o *OriginatorClass) GetAssetType() *AssetType {
	if o == nil {
		return nil
	}

	return o.R.GetAssetType()
}

func (r *originatorClassR) GetAssetType() *AssetType {
	if r == nil {
		return nil
	}

	return r.AssetType
}

func (o *OriginatorClass) GetParamReprAssetTypeMappings() ParamReprAssetTypeMappingSlice {
	if o == nil {
		return nil
	}

	return o.R.GetParamReprAssetTypeMappings()
}

func (r *originatorClassR) GetParamReprAssetTypeMappings() ParamReprAssetTypeMappingSlice {
	if r == nil {
		return nil
	}

	return r.ParamReprAssetTypeMappings
}

func (o *OriginatorClass) GetTelemetries() TelemetrySlice {
	if o == nil {
		return nil
	}

	return o.R.GetTelemetries()
}

func (r *originatorClassR) GetTelemetries() TelemetrySlice {
	if r == nil {
		return nil
	}

	return r.Telemetries
}

// originatorClassL is where Load methods for each relationship are stored.
type originatorClassL struct{}

var (
	originatorClassAllColumns            = []string{"id", "asset_type_id", "code", "alias"}
	originatorClassColumnsWithoutDefault = []string{"asset_type_id", "code"}
	originatorClassColumnsWithDefault    = []string{"id", "alias"}
	originatorClassPrimaryKeyColumns     = []string{"id"}
	originatorClassGeneratedColumns      = []string{}
)

type (
	// OriginatorClassSlice is an alias for a slice of pointers to OriginatorClass.
	// This should almost always be used instead of []OriginatorClass.
	OriginatorClassSlice []*OriginatorClass
	// OriginatorClassHook is the signature for custom OriginatorClass hook methods
	OriginatorClassHook func(context.Context, boil.ContextExecutor, *OriginatorClass) error

	originatorClassQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	originatorClassType                 = reflect.TypeOf(&OriginatorClass{})
	originatorClassMapping              = queries.MakeStructMapping(originatorClassType)
	originatorClassPrimaryKeyMapping, _ = queries.BindMapping(originatorClassType, originatorClassMapping, originatorClassPrimaryKeyColumns)
	originatorClassInsertCacheMut       sync.RWMutex
	originatorClassInsertCache          = make(map[string]insertCache)
	originatorClassUpdateCacheMut       sync.RWMutex
	originatorClassUpdateCache          = make(map[string]updateCache)
	originatorClassUpsertCacheMut       sync.RWMutex
	originatorClassUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var originatorClassAfterSelectMu sync.Mutex
var originatorClassAfterSelectHooks []OriginatorClassHook

var originatorClassBeforeInsertMu sync.Mutex
var originatorClassBeforeInsertHooks []OriginatorClassHook
var originatorClassAfterInsertMu sync.Mutex
var originatorClassAfterInsertHooks []OriginatorClassHook

var originatorClassBeforeUpdateMu sync.Mutex
var originatorClassBeforeUpdateHooks []OriginatorClassHook
var originatorClassAfterUpdateMu sync.Mutex
var originatorClassAfterUpdateHooks []OriginatorClassHook

var originatorClassBeforeDeleteMu sync.Mutex
var originatorClassBeforeDeleteHooks []OriginatorClassHook
var originatorClassAfterDeleteMu sync.Mutex
var originatorClassAfterDeleteHooks []OriginatorClassHook

var originatorClassBeforeUpsertMu sync.Mutex
var originatorClassBeforeUpsertHooks []OriginatorClassHook
var originatorClassAfterUpsertMu sync.Mutex
var originatorClassAfterUpsertHooks []OriginatorClassHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *OriginatorClass) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *OriginatorClass) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *OriginatorClass) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *OriginatorClass) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *OriginatorClass) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *OriginatorClass) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *OriginatorClass) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *OriginatorClass) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *OriginatorClass) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range originatorClassAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOriginatorClassHook registers your hook function for all future operations.
func AddOriginatorClassHook(hookPoint boil.HookPoint, originatorClassHook OriginatorClassHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		originatorClassAfterSelectMu.Lock()
		originatorClassAfterSelectHooks = append(originatorClassAfterSelectHooks, originatorClassHook)
		originatorClassAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		originatorClassBeforeInsertMu.Lock()
		originatorClassBeforeInsertHooks = append(originatorClassBeforeInsertHooks, originatorClassHook)
		originatorClassBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		originatorClassAfterInsertMu.Lock()
		originatorClassAfterInsertHooks = append(originatorClassAfterInsertHooks, originatorClassHook)
		originatorClassAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		originatorClassBeforeUpdateMu.Lock()
		originatorClassBeforeUpdateHooks = append(originatorClassBeforeUpdateHooks, originatorClassHook)
		originatorClassBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		originatorClassAfterUpdateMu.Lock()
		originatorClassAfterUpdateHooks = append(originatorClassAfterUpdateHooks, originatorClassHook)
		originatorClassAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		originatorClassBeforeDeleteMu.Lock()
		originatorClassBeforeDeleteHooks = append(originatorClassBeforeDeleteHooks, originatorClassHook)
		originatorClassBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		originatorClassAfterDeleteMu.Lock()
		originatorClassAfterDeleteHooks = append(originatorClassAfterDeleteHooks, originatorClassHook)
		originatorClassAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		originatorClassBeforeUpsertMu.Lock()
		originatorClassBeforeUpsertHooks = append(originatorClassBeforeUpsertHooks, originatorClassHook)
		originatorClassBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		originatorClassAfterUpsertMu.Lock()
		originatorClassAfterUpsertHooks = append(originatorClassAfterUpsertHooks, originatorClassHook)
		originatorClassAfterUpsertMu.Unlock()
	}
}

// OneG returns a single originatorClass record from the query using the global executor.
func (q originatorClassQuery) OneG(ctx context.Context) (*OriginatorClass, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single originatorClass record from the query.
func (q originatorClassQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OriginatorClass, error) {
	o := &OriginatorClass{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for originator_class")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all OriginatorClass records from the query using the global executor.
func (q originatorClassQuery) AllG(ctx context.Context) (OriginatorClassSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all OriginatorClass records from the query.
func (q originatorClassQuery) All(ctx context.Context, exec boil.ContextExecutor) (OriginatorClassSlice, error) {
	var o []*OriginatorClass

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to OriginatorClass slice")
	}

	if len(originatorClassAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all OriginatorClass records in the query using the global executor
func (q originatorClassQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all OriginatorClass records in the query.
func (q originatorClassQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count originator_class rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q originatorClassQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q originatorClassQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if originator_class exists")
	}

	return count > 0, nil
}

// AssetType pointed to by the foreign key.
func (o *OriginatorClass) AssetType(mods ...qm.QueryMod) assetTypeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AssetTypeID),
	}

	queryMods = append(queryMods, mods...)

	return AssetTypes(queryMods...)
}

// ParamReprAssetTypeMappings retrieves all the param_repr_asset_type_mapping's ParamReprAssetTypeMappings with an executor.
func (o *OriginatorClass) ParamReprAssetTypeMappings(mods ...qm.QueryMod) paramReprAssetTypeMappingQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"param_repr_asset_type_mapping\".\"originator_class_id\"=?", o.ID),
	)

	return ParamReprAssetTypeMappings(queryMods...)
}

// Telemetries retrieves all the telemetry's Telemetries with an executor.
func (o *OriginatorClass) Telemetries(mods ...qm.QueryMod) telemetryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"telemetry\".\"originator_class_id\"=?", o.ID),
	)

	return Telemetries(queryMods...)
}

// LoadAssetType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (originatorClassL) LoadAssetType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOriginatorClass interface{}, mods queries.Applicator) error {
	var slice []*OriginatorClass
	var object *OriginatorClass

	if singular {
		var ok bool
		object, ok = maybeOriginatorClass.(*OriginatorClass)
		if !ok {
			object = new(OriginatorClass)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOriginatorClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOriginatorClass))
			}
		}
	} else {
		s, ok := maybeOriginatorClass.(*[]*OriginatorClass)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOriginatorClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOriginatorClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &originatorClassR{}
		}
		args[object.AssetTypeID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &originatorClassR{}
			}

			args[obj.AssetTypeID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`asset_type`),
		qm.WhereIn(`asset_type.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AssetType")
	}

	var resultSlice []*AssetType
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AssetType")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for asset_type")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for asset_type")
	}

	if len(assetTypeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.AssetType = foreign
		if foreign.R == nil {
			foreign.R = &assetTypeR{}
		}
		foreign.R.OriginatorClasses = append(foreign.R.OriginatorClasses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AssetTypeID == foreign.ID {
				local.R.AssetType = foreign
				if foreign.R == nil {
					foreign.R = &assetTypeR{}
				}
				foreign.R.OriginatorClasses = append(foreign.R.OriginatorClasses, local)
				break
			}
		}
	}

	return nil
}

// LoadParamReprAssetTypeMappings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (originatorClassL) LoadParamReprAssetTypeMappings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOriginatorClass interface{}, mods queries.Applicator) error {
	var slice []*OriginatorClass
	var object *OriginatorClass

	if singular {
		var ok bool
		object, ok = maybeOriginatorClass.(*OriginatorClass)
		if !ok {
			object = new(OriginatorClass)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOriginatorClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOriginatorClass))
			}
		}
	} else {
		s, ok := maybeOriginatorClass.(*[]*OriginatorClass)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOriginatorClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOriginatorClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &originatorClassR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &originatorClassR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`param_repr_asset_type_mapping`),
		qm.WhereIn(`param_repr_asset_type_mapping.originator_class_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load param_repr_asset_type_mapping")
	}

	var resultSlice []*ParamReprAssetTypeMapping
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice param_repr_asset_type_mapping")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on param_repr_asset_type_mapping")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for param_repr_asset_type_mapping")
	}

	if len(paramReprAssetTypeMappingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ParamReprAssetTypeMappings = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &paramReprAssetTypeMappingR{}
			}
			foreign.R.OriginatorClass = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OriginatorClassID {
				local.R.ParamReprAssetTypeMappings = append(local.R.ParamReprAssetTypeMappings, foreign)
				if foreign.R == nil {
					foreign.R = &paramReprAssetTypeMappingR{}
				}
				foreign.R.OriginatorClass = local
				break
			}
		}
	}

	return nil
}

// LoadTelemetries allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (originatorClassL) LoadTelemetries(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOriginatorClass interface{}, mods queries.Applicator) error {
	var slice []*OriginatorClass
	var object *OriginatorClass

	if singular {
		var ok bool
		object, ok = maybeOriginatorClass.(*OriginatorClass)
		if !ok {
			object = new(OriginatorClass)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOriginatorClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOriginatorClass))
			}
		}
	} else {
		s, ok := maybeOriginatorClass.(*[]*OriginatorClass)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOriginatorClass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOriginatorClass))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &originatorClassR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &originatorClassR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`telemetry`),
		qm.WhereIn(`telemetry.originator_class_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load telemetry")
	}

	var resultSlice []*Telemetry
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice telemetry")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on telemetry")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for telemetry")
	}

	if len(telemetryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Telemetries = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &telemetryR{}
			}
			foreign.R.OriginatorClass = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OriginatorClassID {
				local.R.Telemetries = append(local.R.Telemetries, foreign)
				if foreign.R == nil {
					foreign.R = &telemetryR{}
				}
				foreign.R.OriginatorClass = local
				break
			}
		}
	}

	return nil
}

// SetAssetTypeG of the originatorClass to the related item.
// Sets o.R.AssetType to related.
// Adds o to related.R.OriginatorClasses.
// Uses the global database handle.
func (o *OriginatorClass) SetAssetTypeG(ctx context.Context, insert bool, related *AssetType) error {
	return o.SetAssetType(ctx, boil.GetContextDB(), insert, related)
}

// SetAssetType of the originatorClass to the related item.
// Sets o.R.AssetType to related.
// Adds o to related.R.OriginatorClasses.
func (o *OriginatorClass) SetAssetType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AssetType) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"originator_class\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"asset_type_id"}),
		strmangle.WhereClause("\"", "\"", 2, originatorClassPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AssetTypeID = related.ID
	if o.R == nil {
		o.R = &originatorClassR{
			AssetType: related,
		}
	} else {
		o.R.AssetType = related
	}

	if related.R == nil {
		related.R = &assetTypeR{
			OriginatorClasses: OriginatorClassSlice{o},
		}
	} else {
		related.R.OriginatorClasses = append(related.R.OriginatorClasses, o)
	}

	return nil
}

// AddParamReprAssetTypeMappingsG adds the given related objects to the existing relationships
// of the originator_class, optionally inserting them as new records.
// Appends related to o.R.ParamReprAssetTypeMappings.
// Sets related.R.OriginatorClass appropriately.
// Uses the global database handle.
func (o *OriginatorClass) AddParamReprAssetTypeMappingsG(ctx context.Context, insert bool, related ...*ParamReprAssetTypeMapping) error {
	return o.AddParamReprAssetTypeMappings(ctx, boil.GetContextDB(), insert, related...)
}

// AddParamReprAssetTypeMappings adds the given related objects to the existing relationships
// of the originator_class, optionally inserting them as new records.
// Appends related to o.R.ParamReprAssetTypeMappings.
// Sets related.R.OriginatorClass appropriately.
func (o *OriginatorClass) AddParamReprAssetTypeMappings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ParamReprAssetTypeMapping) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OriginatorClassID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"originator_class_id"}),
				strmangle.WhereClause("\"", "\"", 2, paramReprAssetTypeMappingPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OriginatorClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &originatorClassR{
			ParamReprAssetTypeMappings: related,
		}
	} else {
		o.R.ParamReprAssetTypeMappings = append(o.R.ParamReprAssetTypeMappings, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &paramReprAssetTypeMappingR{
				OriginatorClass: o,
			}
		} else {
			rel.R.OriginatorClass = o
		}
	}
	return nil
}

// AddTelemetriesG adds the given related objects to the existing relationships
// of the originator_class, optionally inserting them as new records.
// Appends related to o.R.Telemetries.
// Sets related.R.OriginatorClass appropriately.
// Uses the global database handle.
func (o *OriginatorClass) AddTelemetriesG(ctx context.Context, insert bool, related ...*Telemetry) error {
	return o.AddTelemetries(ctx, boil.GetContextDB(), insert, related...)
}

// AddTelemetries adds the given related objects to the existing relationships
// of the originator_class, optionally inserting them as new records.
// Appends related to o.R.Telemetries.
// Sets related.R.OriginatorClass appropriately.
func (o *OriginatorClass) AddTelemetries(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Telemetry) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OriginatorClassID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"telemetry\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"originator_class_id"}),
				strmangle.WhereClause("\"", "\"", 2, telemetryPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.AssetID, rel.OriginatorClassID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OriginatorClassID = o.ID
		}
	}

	if o.R == nil {
		o.R = &originatorClassR{
			Telemetries: related,
		}
	} else {
		o.R.Telemetries = append(o.R.Telemetries, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &telemetryR{
				OriginatorClass: o,
			}
		} else {
			rel.R.OriginatorClass = o
		}
	}
	return nil
}

// OriginatorClasses retrieves all the records using an executor.
func OriginatorClasses(mods ...qm.QueryMod) originatorClassQuery {
	mods = append(mods, qm.From("\"originator_class\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"originator_class\".*"})
	}

	return originatorClassQuery{q}
}

// FindOriginatorClassG retrieves a single record by ID.
func FindOriginatorClassG(ctx context.Context, iD int, selectCols ...string) (*OriginatorClass, error) {
	return FindOriginatorClass(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindOriginatorClass retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOriginatorClass(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*OriginatorClass, error) {
	originatorClassObj := &OriginatorClass{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"originator_class\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, originatorClassObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from originator_class")
	}

	if err = originatorClassObj.doAfterSelectHooks(ctx, exec); err != nil {
		return originatorClassObj, err
	}

	return originatorClassObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *OriginatorClass) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OriginatorClass) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no originator_class provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(originatorClassColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	originatorClassInsertCacheMut.RLock()
	cache, cached := originatorClassInsertCache[key]
	originatorClassInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			originatorClassAllColumns,
			originatorClassColumnsWithDefault,
			originatorClassColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(originatorClassType, originatorClassMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(originatorClassType, originatorClassMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"originator_class\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"originator_class\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into originator_class")
	}

	if !cached {
		originatorClassInsertCacheMut.Lock()
		originatorClassInsertCache[key] = cache
		originatorClassInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single OriginatorClass record using the global executor.
// See Update for more documentation.
func (o *OriginatorClass) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the OriginatorClass.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OriginatorClass) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	originatorClassUpdateCacheMut.RLock()
	cache, cached := originatorClassUpdateCache[key]
	originatorClassUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			originatorClassAllColumns,
			originatorClassPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update originator_class, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"originator_class\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, originatorClassPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(originatorClassType, originatorClassMapping, append(wl, originatorClassPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update originator_class row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for originator_class")
	}

	if !cached {
		originatorClassUpdateCacheMut.Lock()
		originatorClassUpdateCache[key] = cache
		originatorClassUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q originatorClassQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q originatorClassQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for originator_class")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for originator_class")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o OriginatorClassSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OriginatorClassSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), originatorClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"originator_class\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, originatorClassPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in originatorClass slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all originatorClass")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *OriginatorClass) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OriginatorClass) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no originator_class provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(originatorClassColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	originatorClassUpsertCacheMut.RLock()
	cache, cached := originatorClassUpsertCache[key]
	originatorClassUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			originatorClassAllColumns,
			originatorClassColumnsWithDefault,
			originatorClassColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			originatorClassAllColumns,
			originatorClassPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert originator_class, could not build update column list")
		}

		ret := strmangle.SetComplement(originatorClassAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(originatorClassPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert originator_class, could not build conflict column list")
			}

			conflict = make([]string, len(originatorClassPrimaryKeyColumns))
			copy(conflict, originatorClassPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"originator_class\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(originatorClassType, originatorClassMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(originatorClassType, originatorClassMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert originator_class")
	}

	if !cached {
		originatorClassUpsertCacheMut.Lock()
		originatorClassUpsertCache[key] = cache
		originatorClassUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single OriginatorClass record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *OriginatorClass) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single OriginatorClass record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OriginatorClass) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no OriginatorClass provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), originatorClassPrimaryKeyMapping)
	sql := "DELETE FROM \"originator_class\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from originator_class")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for originator_class")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q originatorClassQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q originatorClassQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no originatorClassQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from originator_class")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for originator_class")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o OriginatorClassSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OriginatorClassSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(originatorClassBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), originatorClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"originator_class\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, originatorClassPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from originatorClass slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for originator_class")
	}

	if len(originatorClassAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *OriginatorClass) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no OriginatorClass provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OriginatorClass) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOriginatorClass(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OriginatorClassSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty OriginatorClassSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OriginatorClassSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OriginatorClassSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), originatorClassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"originator_class\".* FROM \"originator_class\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, originatorClassPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OriginatorClassSlice")
	}

	*o = slice

	return nil
}

// OriginatorClassExistsG checks if the OriginatorClass row exists.
func OriginatorClassExistsG(ctx context.Context, iD int) (bool, error) {
	return OriginatorClassExists(ctx, boil.GetContextDB(), iD)
}

// OriginatorClassExists checks if the OriginatorClass row exists.
func OriginatorClassExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"originator_class\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if originator_class exists")
	}

	return exists, nil
}

// Exists checks if the OriginatorClass row exists.
func (o *OriginatorClass) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OriginatorClassExists(ctx, exec, o.ID)
}
