// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ParamType is an object representing the database table.
type ParamType struct {
	ID      int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Code    string `boil:"code" json:"code" toml:"code" yaml:"code"`
	Alias   string `boil:"alias" json:"alias" toml:"alias" yaml:"alias"`
	HexCode string `boil:"hex_code" json:"hex_code" toml:"hex_code" yaml:"hex_code"`

	R *paramTypeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L paramTypeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ParamTypeColumns = struct {
	ID      string
	Code    string
	Alias   string
	HexCode string
}{
	ID:      "id",
	Code:    "code",
	Alias:   "alias",
	HexCode: "hex_code",
}

var ParamTypeTableColumns = struct {
	ID      string
	Code    string
	Alias   string
	HexCode string
}{
	ID:      "param_type.id",
	Code:    "param_type.code",
	Alias:   "param_type.alias",
	HexCode: "param_type.hex_code",
}

// Generated where

var ParamTypeWhere = struct {
	ID      whereHelperint
	Code    whereHelperstring
	Alias   whereHelperstring
	HexCode whereHelperstring
}{
	ID:      whereHelperint{field: "\"param_type\".\"id\""},
	Code:    whereHelperstring{field: "\"param_type\".\"code\""},
	Alias:   whereHelperstring{field: "\"param_type\".\"alias\""},
	HexCode: whereHelperstring{field: "\"param_type\".\"hex_code\""},
}

// ParamTypeRels is where relationship names are stored.
var ParamTypeRels = struct {
	ParamReprAssetTypeMappings string
}{
	ParamReprAssetTypeMappings: "ParamReprAssetTypeMappings",
}

// paramTypeR is where relationships are stored.
type paramTypeR struct {
	ParamReprAssetTypeMappings ParamReprAssetTypeMappingSlice `boil:"ParamReprAssetTypeMappings" json:"ParamReprAssetTypeMappings" toml:"ParamReprAssetTypeMappings" yaml:"ParamReprAssetTypeMappings"`
}

// NewStruct creates a new relationship struct
func (*paramTypeR) NewStruct() *paramTypeR {
	return &paramTypeR{}
}

func (o *ParamType) GetParamReprAssetTypeMappings() ParamReprAssetTypeMappingSlice {
	if o == nil {
		return nil
	}

	return o.R.GetParamReprAssetTypeMappings()
}

func (r *paramTypeR) GetParamReprAssetTypeMappings() ParamReprAssetTypeMappingSlice {
	if r == nil {
		return nil
	}

	return r.ParamReprAssetTypeMappings
}

// paramTypeL is where Load methods for each relationship are stored.
type paramTypeL struct{}

var (
	paramTypeAllColumns            = []string{"id", "code", "alias", "hex_code"}
	paramTypeColumnsWithoutDefault = []string{"code", "alias", "hex_code"}
	paramTypeColumnsWithDefault    = []string{"id"}
	paramTypePrimaryKeyColumns     = []string{"id"}
	paramTypeGeneratedColumns      = []string{}
)

type (
	// ParamTypeSlice is an alias for a slice of pointers to ParamType.
	// This should almost always be used instead of []ParamType.
	ParamTypeSlice []*ParamType
	// ParamTypeHook is the signature for custom ParamType hook methods
	ParamTypeHook func(context.Context, boil.ContextExecutor, *ParamType) error

	paramTypeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	paramTypeType                 = reflect.TypeOf(&ParamType{})
	paramTypeMapping              = queries.MakeStructMapping(paramTypeType)
	paramTypePrimaryKeyMapping, _ = queries.BindMapping(paramTypeType, paramTypeMapping, paramTypePrimaryKeyColumns)
	paramTypeInsertCacheMut       sync.RWMutex
	paramTypeInsertCache          = make(map[string]insertCache)
	paramTypeUpdateCacheMut       sync.RWMutex
	paramTypeUpdateCache          = make(map[string]updateCache)
	paramTypeUpsertCacheMut       sync.RWMutex
	paramTypeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var paramTypeAfterSelectMu sync.Mutex
var paramTypeAfterSelectHooks []ParamTypeHook

var paramTypeBeforeInsertMu sync.Mutex
var paramTypeBeforeInsertHooks []ParamTypeHook
var paramTypeAfterInsertMu sync.Mutex
var paramTypeAfterInsertHooks []ParamTypeHook

var paramTypeBeforeUpdateMu sync.Mutex
var paramTypeBeforeUpdateHooks []ParamTypeHook
var paramTypeAfterUpdateMu sync.Mutex
var paramTypeAfterUpdateHooks []ParamTypeHook

var paramTypeBeforeDeleteMu sync.Mutex
var paramTypeBeforeDeleteHooks []ParamTypeHook
var paramTypeAfterDeleteMu sync.Mutex
var paramTypeAfterDeleteHooks []ParamTypeHook

var paramTypeBeforeUpsertMu sync.Mutex
var paramTypeBeforeUpsertHooks []ParamTypeHook
var paramTypeAfterUpsertMu sync.Mutex
var paramTypeAfterUpsertHooks []ParamTypeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ParamType) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ParamType) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ParamType) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ParamType) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ParamType) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ParamType) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ParamType) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ParamType) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ParamType) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramTypeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddParamTypeHook registers your hook function for all future operations.
func AddParamTypeHook(hookPoint boil.HookPoint, paramTypeHook ParamTypeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		paramTypeAfterSelectMu.Lock()
		paramTypeAfterSelectHooks = append(paramTypeAfterSelectHooks, paramTypeHook)
		paramTypeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		paramTypeBeforeInsertMu.Lock()
		paramTypeBeforeInsertHooks = append(paramTypeBeforeInsertHooks, paramTypeHook)
		paramTypeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		paramTypeAfterInsertMu.Lock()
		paramTypeAfterInsertHooks = append(paramTypeAfterInsertHooks, paramTypeHook)
		paramTypeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		paramTypeBeforeUpdateMu.Lock()
		paramTypeBeforeUpdateHooks = append(paramTypeBeforeUpdateHooks, paramTypeHook)
		paramTypeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		paramTypeAfterUpdateMu.Lock()
		paramTypeAfterUpdateHooks = append(paramTypeAfterUpdateHooks, paramTypeHook)
		paramTypeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		paramTypeBeforeDeleteMu.Lock()
		paramTypeBeforeDeleteHooks = append(paramTypeBeforeDeleteHooks, paramTypeHook)
		paramTypeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		paramTypeAfterDeleteMu.Lock()
		paramTypeAfterDeleteHooks = append(paramTypeAfterDeleteHooks, paramTypeHook)
		paramTypeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		paramTypeBeforeUpsertMu.Lock()
		paramTypeBeforeUpsertHooks = append(paramTypeBeforeUpsertHooks, paramTypeHook)
		paramTypeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		paramTypeAfterUpsertMu.Lock()
		paramTypeAfterUpsertHooks = append(paramTypeAfterUpsertHooks, paramTypeHook)
		paramTypeAfterUpsertMu.Unlock()
	}
}

// OneG returns a single paramType record from the query using the global executor.
func (q paramTypeQuery) OneG(ctx context.Context) (*ParamType, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single paramType record from the query.
func (q paramTypeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ParamType, error) {
	o := &ParamType{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for param_type")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ParamType records from the query using the global executor.
func (q paramTypeQuery) AllG(ctx context.Context) (ParamTypeSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ParamType records from the query.
func (q paramTypeQuery) All(ctx context.Context, exec boil.ContextExecutor) (ParamTypeSlice, error) {
	var o []*ParamType

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ParamType slice")
	}

	if len(paramTypeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ParamType records in the query using the global executor
func (q paramTypeQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ParamType records in the query.
func (q paramTypeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count param_type rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q paramTypeQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q paramTypeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if param_type exists")
	}

	return count > 0, nil
}

// ParamReprAssetTypeMappings retrieves all the param_repr_asset_type_mapping's ParamReprAssetTypeMappings with an executor.
func (o *ParamType) ParamReprAssetTypeMappings(mods ...qm.QueryMod) paramReprAssetTypeMappingQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"param_repr_asset_type_mapping\".\"param_type_id\"=?", o.ID),
	)

	return ParamReprAssetTypeMappings(queryMods...)
}

// LoadParamReprAssetTypeMappings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (paramTypeL) LoadParamReprAssetTypeMappings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeParamType interface{}, mods queries.Applicator) error {
	var slice []*ParamType
	var object *ParamType

	if singular {
		var ok bool
		object, ok = maybeParamType.(*ParamType)
		if !ok {
			object = new(ParamType)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeParamType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeParamType))
			}
		}
	} else {
		s, ok := maybeParamType.(*[]*ParamType)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeParamType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeParamType))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &paramTypeR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &paramTypeR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`param_repr_asset_type_mapping`),
		qm.WhereIn(`param_repr_asset_type_mapping.param_type_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load param_repr_asset_type_mapping")
	}

	var resultSlice []*ParamReprAssetTypeMapping
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice param_repr_asset_type_mapping")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on param_repr_asset_type_mapping")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for param_repr_asset_type_mapping")
	}

	if len(paramReprAssetTypeMappingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ParamReprAssetTypeMappings = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &paramReprAssetTypeMappingR{}
			}
			foreign.R.ParamType = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ParamTypeID {
				local.R.ParamReprAssetTypeMappings = append(local.R.ParamReprAssetTypeMappings, foreign)
				if foreign.R == nil {
					foreign.R = &paramReprAssetTypeMappingR{}
				}
				foreign.R.ParamType = local
				break
			}
		}
	}

	return nil
}

// AddParamReprAssetTypeMappingsG adds the given related objects to the existing relationships
// of the param_type, optionally inserting them as new records.
// Appends related to o.R.ParamReprAssetTypeMappings.
// Sets related.R.ParamType appropriately.
// Uses the global database handle.
func (o *ParamType) AddParamReprAssetTypeMappingsG(ctx context.Context, insert bool, related ...*ParamReprAssetTypeMapping) error {
	return o.AddParamReprAssetTypeMappings(ctx, boil.GetContextDB(), insert, related...)
}

// AddParamReprAssetTypeMappings adds the given related objects to the existing relationships
// of the param_type, optionally inserting them as new records.
// Appends related to o.R.ParamReprAssetTypeMappings.
// Sets related.R.ParamType appropriately.
func (o *ParamType) AddParamReprAssetTypeMappings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ParamReprAssetTypeMapping) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ParamTypeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"param_type_id"}),
				strmangle.WhereClause("\"", "\"", 2, paramReprAssetTypeMappingPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ParamTypeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &paramTypeR{
			ParamReprAssetTypeMappings: related,
		}
	} else {
		o.R.ParamReprAssetTypeMappings = append(o.R.ParamReprAssetTypeMappings, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &paramReprAssetTypeMappingR{
				ParamType: o,
			}
		} else {
			rel.R.ParamType = o
		}
	}
	return nil
}

// ParamTypes retrieves all the records using an executor.
func ParamTypes(mods ...qm.QueryMod) paramTypeQuery {
	mods = append(mods, qm.From("\"param_type\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"param_type\".*"})
	}

	return paramTypeQuery{q}
}

// FindParamTypeG retrieves a single record by ID.
func FindParamTypeG(ctx context.Context, iD int, selectCols ...string) (*ParamType, error) {
	return FindParamType(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindParamType retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindParamType(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*ParamType, error) {
	paramTypeObj := &ParamType{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"param_type\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, paramTypeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from param_type")
	}

	if err = paramTypeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return paramTypeObj, err
	}

	return paramTypeObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ParamType) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ParamType) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no param_type provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(paramTypeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	paramTypeInsertCacheMut.RLock()
	cache, cached := paramTypeInsertCache[key]
	paramTypeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			paramTypeAllColumns,
			paramTypeColumnsWithDefault,
			paramTypeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(paramTypeType, paramTypeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(paramTypeType, paramTypeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"param_type\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"param_type\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into param_type")
	}

	if !cached {
		paramTypeInsertCacheMut.Lock()
		paramTypeInsertCache[key] = cache
		paramTypeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single ParamType record using the global executor.
// See Update for more documentation.
func (o *ParamType) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ParamType.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ParamType) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	paramTypeUpdateCacheMut.RLock()
	cache, cached := paramTypeUpdateCache[key]
	paramTypeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			paramTypeAllColumns,
			paramTypePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update param_type, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"param_type\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, paramTypePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(paramTypeType, paramTypeMapping, append(wl, paramTypePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update param_type row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for param_type")
	}

	if !cached {
		paramTypeUpdateCacheMut.Lock()
		paramTypeUpdateCache[key] = cache
		paramTypeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q paramTypeQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q paramTypeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for param_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for param_type")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ParamTypeSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ParamTypeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paramTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"param_type\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, paramTypePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in paramType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all paramType")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ParamType) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ParamType) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no param_type provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(paramTypeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	paramTypeUpsertCacheMut.RLock()
	cache, cached := paramTypeUpsertCache[key]
	paramTypeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			paramTypeAllColumns,
			paramTypeColumnsWithDefault,
			paramTypeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			paramTypeAllColumns,
			paramTypePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert param_type, could not build update column list")
		}

		ret := strmangle.SetComplement(paramTypeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(paramTypePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert param_type, could not build conflict column list")
			}

			conflict = make([]string, len(paramTypePrimaryKeyColumns))
			copy(conflict, paramTypePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"param_type\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(paramTypeType, paramTypeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(paramTypeType, paramTypeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert param_type")
	}

	if !cached {
		paramTypeUpsertCacheMut.Lock()
		paramTypeUpsertCache[key] = cache
		paramTypeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single ParamType record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ParamType) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ParamType record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ParamType) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ParamType provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), paramTypePrimaryKeyMapping)
	sql := "DELETE FROM \"param_type\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from param_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for param_type")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q paramTypeQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q paramTypeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no paramTypeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from param_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for param_type")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ParamTypeSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ParamTypeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(paramTypeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paramTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"param_type\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, paramTypePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from paramType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for param_type")
	}

	if len(paramTypeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ParamType) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ParamType provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ParamType) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindParamType(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ParamTypeSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ParamTypeSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ParamTypeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ParamTypeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paramTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"param_type\".* FROM \"param_type\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, paramTypePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ParamTypeSlice")
	}

	*o = slice

	return nil
}

// ParamTypeExistsG checks if the ParamType row exists.
func ParamTypeExistsG(ctx context.Context, iD int) (bool, error) {
	return ParamTypeExists(ctx, boil.GetContextDB(), iD)
}

// ParamTypeExists checks if the ParamType row exists.
func ParamTypeExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"param_type\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if param_type exists")
	}

	return exists, nil
}

// Exists checks if the ParamType row exists.
func (o *ParamType) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ParamTypeExists(ctx, exec, o.ID)
}
