// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ParamReprAssetTypeMapping is an object representing the database table.
type ParamReprAssetTypeMapping struct {
	ID                int `boil:"id" json:"id" toml:"id" yaml:"id"`
	ParamTypeID       int `boil:"param_type_id" json:"param_type_id" toml:"param_type_id" yaml:"param_type_id"`
	ParamReprID       int `boil:"param_repr_id" json:"param_repr_id" toml:"param_repr_id" yaml:"param_repr_id"`
	AssetTypeID       int `boil:"asset_type_id" json:"asset_type_id" toml:"asset_type_id" yaml:"asset_type_id"`
	OriginatorClassID int `boil:"originator_class_id" json:"originator_class_id" toml:"originator_class_id" yaml:"originator_class_id"`

	R *paramReprAssetTypeMappingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L paramReprAssetTypeMappingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ParamReprAssetTypeMappingColumns = struct {
	ID                string
	ParamTypeID       string
	ParamReprID       string
	AssetTypeID       string
	OriginatorClassID string
}{
	ID:                "id",
	ParamTypeID:       "param_type_id",
	ParamReprID:       "param_repr_id",
	AssetTypeID:       "asset_type_id",
	OriginatorClassID: "originator_class_id",
}

var ParamReprAssetTypeMappingTableColumns = struct {
	ID                string
	ParamTypeID       string
	ParamReprID       string
	AssetTypeID       string
	OriginatorClassID string
}{
	ID:                "param_repr_asset_type_mapping.id",
	ParamTypeID:       "param_repr_asset_type_mapping.param_type_id",
	ParamReprID:       "param_repr_asset_type_mapping.param_repr_id",
	AssetTypeID:       "param_repr_asset_type_mapping.asset_type_id",
	OriginatorClassID: "param_repr_asset_type_mapping.originator_class_id",
}

// Generated where

var ParamReprAssetTypeMappingWhere = struct {
	ID                whereHelperint
	ParamTypeID       whereHelperint
	ParamReprID       whereHelperint
	AssetTypeID       whereHelperint
	OriginatorClassID whereHelperint
}{
	ID:                whereHelperint{field: "\"param_repr_asset_type_mapping\".\"id\""},
	ParamTypeID:       whereHelperint{field: "\"param_repr_asset_type_mapping\".\"param_type_id\""},
	ParamReprID:       whereHelperint{field: "\"param_repr_asset_type_mapping\".\"param_repr_id\""},
	AssetTypeID:       whereHelperint{field: "\"param_repr_asset_type_mapping\".\"asset_type_id\""},
	OriginatorClassID: whereHelperint{field: "\"param_repr_asset_type_mapping\".\"originator_class_id\""},
}

// ParamReprAssetTypeMappingRels is where relationship names are stored.
var ParamReprAssetTypeMappingRels = struct {
	AssetType       string
	OriginatorClass string
	ParamRepr       string
	ParamType       string
}{
	AssetType:       "AssetType",
	OriginatorClass: "OriginatorClass",
	ParamRepr:       "ParamRepr",
	ParamType:       "ParamType",
}

// paramReprAssetTypeMappingR is where relationships are stored.
type paramReprAssetTypeMappingR struct {
	AssetType       *AssetType       `boil:"AssetType" json:"AssetType" toml:"AssetType" yaml:"AssetType"`
	OriginatorClass *OriginatorClass `boil:"OriginatorClass" json:"OriginatorClass" toml:"OriginatorClass" yaml:"OriginatorClass"`
	ParamRepr       *ParamRepr       `boil:"ParamRepr" json:"ParamRepr" toml:"ParamRepr" yaml:"ParamRepr"`
	ParamType       *ParamType       `boil:"ParamType" json:"ParamType" toml:"ParamType" yaml:"ParamType"`
}

// NewStruct creates a new relationship struct
func (*paramReprAssetTypeMappingR) NewStruct() *paramReprAssetTypeMappingR {
	return &paramReprAssetTypeMappingR{}
}

func (o *ParamReprAssetTypeMapping) GetAssetType() *AssetType {
	if o == nil {
		return nil
	}

	return o.R.GetAssetType()
}

func (r *paramReprAssetTypeMappingR) GetAssetType() *AssetType {
	if r == nil {
		return nil
	}

	return r.AssetType
}

func (o *ParamReprAssetTypeMapping) GetOriginatorClass() *OriginatorClass {
	if o == nil {
		return nil
	}

	return o.R.GetOriginatorClass()
}

func (r *paramReprAssetTypeMappingR) GetOriginatorClass() *OriginatorClass {
	if r == nil {
		return nil
	}

	return r.OriginatorClass
}

func (o *ParamReprAssetTypeMapping) GetParamRepr() *ParamRepr {
	if o == nil {
		return nil
	}

	return o.R.GetParamRepr()
}

func (r *paramReprAssetTypeMappingR) GetParamRepr() *ParamRepr {
	if r == nil {
		return nil
	}

	return r.ParamRepr
}

func (o *ParamReprAssetTypeMapping) GetParamType() *ParamType {
	if o == nil {
		return nil
	}

	return o.R.GetParamType()
}

func (r *paramReprAssetTypeMappingR) GetParamType() *ParamType {
	if r == nil {
		return nil
	}

	return r.ParamType
}

// paramReprAssetTypeMappingL is where Load methods for each relationship are stored.
type paramReprAssetTypeMappingL struct{}

var (
	paramReprAssetTypeMappingAllColumns            = []string{"id", "param_type_id", "param_repr_id", "asset_type_id", "originator_class_id"}
	paramReprAssetTypeMappingColumnsWithoutDefault = []string{"param_type_id", "param_repr_id", "asset_type_id", "originator_class_id"}
	paramReprAssetTypeMappingColumnsWithDefault    = []string{"id"}
	paramReprAssetTypeMappingPrimaryKeyColumns     = []string{"id"}
	paramReprAssetTypeMappingGeneratedColumns      = []string{}
)

type (
	// ParamReprAssetTypeMappingSlice is an alias for a slice of pointers to ParamReprAssetTypeMapping.
	// This should almost always be used instead of []ParamReprAssetTypeMapping.
	ParamReprAssetTypeMappingSlice []*ParamReprAssetTypeMapping
	// ParamReprAssetTypeMappingHook is the signature for custom ParamReprAssetTypeMapping hook methods
	ParamReprAssetTypeMappingHook func(context.Context, boil.ContextExecutor, *ParamReprAssetTypeMapping) error

	paramReprAssetTypeMappingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	paramReprAssetTypeMappingType                 = reflect.TypeOf(&ParamReprAssetTypeMapping{})
	paramReprAssetTypeMappingMapping              = queries.MakeStructMapping(paramReprAssetTypeMappingType)
	paramReprAssetTypeMappingPrimaryKeyMapping, _ = queries.BindMapping(paramReprAssetTypeMappingType, paramReprAssetTypeMappingMapping, paramReprAssetTypeMappingPrimaryKeyColumns)
	paramReprAssetTypeMappingInsertCacheMut       sync.RWMutex
	paramReprAssetTypeMappingInsertCache          = make(map[string]insertCache)
	paramReprAssetTypeMappingUpdateCacheMut       sync.RWMutex
	paramReprAssetTypeMappingUpdateCache          = make(map[string]updateCache)
	paramReprAssetTypeMappingUpsertCacheMut       sync.RWMutex
	paramReprAssetTypeMappingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var paramReprAssetTypeMappingAfterSelectMu sync.Mutex
var paramReprAssetTypeMappingAfterSelectHooks []ParamReprAssetTypeMappingHook

var paramReprAssetTypeMappingBeforeInsertMu sync.Mutex
var paramReprAssetTypeMappingBeforeInsertHooks []ParamReprAssetTypeMappingHook
var paramReprAssetTypeMappingAfterInsertMu sync.Mutex
var paramReprAssetTypeMappingAfterInsertHooks []ParamReprAssetTypeMappingHook

var paramReprAssetTypeMappingBeforeUpdateMu sync.Mutex
var paramReprAssetTypeMappingBeforeUpdateHooks []ParamReprAssetTypeMappingHook
var paramReprAssetTypeMappingAfterUpdateMu sync.Mutex
var paramReprAssetTypeMappingAfterUpdateHooks []ParamReprAssetTypeMappingHook

var paramReprAssetTypeMappingBeforeDeleteMu sync.Mutex
var paramReprAssetTypeMappingBeforeDeleteHooks []ParamReprAssetTypeMappingHook
var paramReprAssetTypeMappingAfterDeleteMu sync.Mutex
var paramReprAssetTypeMappingAfterDeleteHooks []ParamReprAssetTypeMappingHook

var paramReprAssetTypeMappingBeforeUpsertMu sync.Mutex
var paramReprAssetTypeMappingBeforeUpsertHooks []ParamReprAssetTypeMappingHook
var paramReprAssetTypeMappingAfterUpsertMu sync.Mutex
var paramReprAssetTypeMappingAfterUpsertHooks []ParamReprAssetTypeMappingHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ParamReprAssetTypeMapping) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ParamReprAssetTypeMapping) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ParamReprAssetTypeMapping) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ParamReprAssetTypeMapping) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ParamReprAssetTypeMapping) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ParamReprAssetTypeMapping) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ParamReprAssetTypeMapping) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ParamReprAssetTypeMapping) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ParamReprAssetTypeMapping) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramReprAssetTypeMappingAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddParamReprAssetTypeMappingHook registers your hook function for all future operations.
func AddParamReprAssetTypeMappingHook(hookPoint boil.HookPoint, paramReprAssetTypeMappingHook ParamReprAssetTypeMappingHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		paramReprAssetTypeMappingAfterSelectMu.Lock()
		paramReprAssetTypeMappingAfterSelectHooks = append(paramReprAssetTypeMappingAfterSelectHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		paramReprAssetTypeMappingBeforeInsertMu.Lock()
		paramReprAssetTypeMappingBeforeInsertHooks = append(paramReprAssetTypeMappingBeforeInsertHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		paramReprAssetTypeMappingAfterInsertMu.Lock()
		paramReprAssetTypeMappingAfterInsertHooks = append(paramReprAssetTypeMappingAfterInsertHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		paramReprAssetTypeMappingBeforeUpdateMu.Lock()
		paramReprAssetTypeMappingBeforeUpdateHooks = append(paramReprAssetTypeMappingBeforeUpdateHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		paramReprAssetTypeMappingAfterUpdateMu.Lock()
		paramReprAssetTypeMappingAfterUpdateHooks = append(paramReprAssetTypeMappingAfterUpdateHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		paramReprAssetTypeMappingBeforeDeleteMu.Lock()
		paramReprAssetTypeMappingBeforeDeleteHooks = append(paramReprAssetTypeMappingBeforeDeleteHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		paramReprAssetTypeMappingAfterDeleteMu.Lock()
		paramReprAssetTypeMappingAfterDeleteHooks = append(paramReprAssetTypeMappingAfterDeleteHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		paramReprAssetTypeMappingBeforeUpsertMu.Lock()
		paramReprAssetTypeMappingBeforeUpsertHooks = append(paramReprAssetTypeMappingBeforeUpsertHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		paramReprAssetTypeMappingAfterUpsertMu.Lock()
		paramReprAssetTypeMappingAfterUpsertHooks = append(paramReprAssetTypeMappingAfterUpsertHooks, paramReprAssetTypeMappingHook)
		paramReprAssetTypeMappingAfterUpsertMu.Unlock()
	}
}

// OneG returns a single paramReprAssetTypeMapping record from the query using the global executor.
func (q paramReprAssetTypeMappingQuery) OneG(ctx context.Context) (*ParamReprAssetTypeMapping, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single paramReprAssetTypeMapping record from the query.
func (q paramReprAssetTypeMappingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ParamReprAssetTypeMapping, error) {
	o := &ParamReprAssetTypeMapping{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for param_repr_asset_type_mapping")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ParamReprAssetTypeMapping records from the query using the global executor.
func (q paramReprAssetTypeMappingQuery) AllG(ctx context.Context) (ParamReprAssetTypeMappingSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ParamReprAssetTypeMapping records from the query.
func (q paramReprAssetTypeMappingQuery) All(ctx context.Context, exec boil.ContextExecutor) (ParamReprAssetTypeMappingSlice, error) {
	var o []*ParamReprAssetTypeMapping

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ParamReprAssetTypeMapping slice")
	}

	if len(paramReprAssetTypeMappingAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ParamReprAssetTypeMapping records in the query using the global executor
func (q paramReprAssetTypeMappingQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ParamReprAssetTypeMapping records in the query.
func (q paramReprAssetTypeMappingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count param_repr_asset_type_mapping rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q paramReprAssetTypeMappingQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q paramReprAssetTypeMappingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if param_repr_asset_type_mapping exists")
	}

	return count > 0, nil
}

// AssetType pointed to by the foreign key.
func (o *ParamReprAssetTypeMapping) AssetType(mods ...qm.QueryMod) assetTypeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AssetTypeID),
	}

	queryMods = append(queryMods, mods...)

	return AssetTypes(queryMods...)
}

// OriginatorClass pointed to by the foreign key.
func (o *ParamReprAssetTypeMapping) OriginatorClass(mods ...qm.QueryMod) originatorClassQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OriginatorClassID),
	}

	queryMods = append(queryMods, mods...)

	return OriginatorClasses(queryMods...)
}

// ParamRepr pointed to by the foreign key.
func (o *ParamReprAssetTypeMapping) ParamRepr(mods ...qm.QueryMod) paramReprQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ParamReprID),
	}

	queryMods = append(queryMods, mods...)

	return ParamReprs(queryMods...)
}

// ParamType pointed to by the foreign key.
func (o *ParamReprAssetTypeMapping) ParamType(mods ...qm.QueryMod) paramTypeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ParamTypeID),
	}

	queryMods = append(queryMods, mods...)

	return ParamTypes(queryMods...)
}

// LoadAssetType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (paramReprAssetTypeMappingL) LoadAssetType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeParamReprAssetTypeMapping interface{}, mods queries.Applicator) error {
	var slice []*ParamReprAssetTypeMapping
	var object *ParamReprAssetTypeMapping

	if singular {
		var ok bool
		object, ok = maybeParamReprAssetTypeMapping.(*ParamReprAssetTypeMapping)
		if !ok {
			object = new(ParamReprAssetTypeMapping)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeParamReprAssetTypeMapping))
			}
		}
	} else {
		s, ok := maybeParamReprAssetTypeMapping.(*[]*ParamReprAssetTypeMapping)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeParamReprAssetTypeMapping))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &paramReprAssetTypeMappingR{}
		}
		args[object.AssetTypeID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &paramReprAssetTypeMappingR{}
			}

			args[obj.AssetTypeID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`asset_type`),
		qm.WhereIn(`asset_type.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AssetType")
	}

	var resultSlice []*AssetType
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AssetType")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for asset_type")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for asset_type")
	}

	if len(assetTypeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.AssetType = foreign
		if foreign.R == nil {
			foreign.R = &assetTypeR{}
		}
		foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AssetTypeID == foreign.ID {
				local.R.AssetType = foreign
				if foreign.R == nil {
					foreign.R = &assetTypeR{}
				}
				foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, local)
				break
			}
		}
	}

	return nil
}

// LoadOriginatorClass allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (paramReprAssetTypeMappingL) LoadOriginatorClass(ctx context.Context, e boil.ContextExecutor, singular bool, maybeParamReprAssetTypeMapping interface{}, mods queries.Applicator) error {
	var slice []*ParamReprAssetTypeMapping
	var object *ParamReprAssetTypeMapping

	if singular {
		var ok bool
		object, ok = maybeParamReprAssetTypeMapping.(*ParamReprAssetTypeMapping)
		if !ok {
			object = new(ParamReprAssetTypeMapping)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeParamReprAssetTypeMapping))
			}
		}
	} else {
		s, ok := maybeParamReprAssetTypeMapping.(*[]*ParamReprAssetTypeMapping)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeParamReprAssetTypeMapping))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &paramReprAssetTypeMappingR{}
		}
		args[object.OriginatorClassID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &paramReprAssetTypeMappingR{}
			}

			args[obj.OriginatorClassID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`originator_class`),
		qm.WhereIn(`originator_class.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load OriginatorClass")
	}

	var resultSlice []*OriginatorClass
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice OriginatorClass")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for originator_class")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for originator_class")
	}

	if len(originatorClassAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.OriginatorClass = foreign
		if foreign.R == nil {
			foreign.R = &originatorClassR{}
		}
		foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.OriginatorClassID == foreign.ID {
				local.R.OriginatorClass = foreign
				if foreign.R == nil {
					foreign.R = &originatorClassR{}
				}
				foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, local)
				break
			}
		}
	}

	return nil
}

// LoadParamRepr allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (paramReprAssetTypeMappingL) LoadParamRepr(ctx context.Context, e boil.ContextExecutor, singular bool, maybeParamReprAssetTypeMapping interface{}, mods queries.Applicator) error {
	var slice []*ParamReprAssetTypeMapping
	var object *ParamReprAssetTypeMapping

	if singular {
		var ok bool
		object, ok = maybeParamReprAssetTypeMapping.(*ParamReprAssetTypeMapping)
		if !ok {
			object = new(ParamReprAssetTypeMapping)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeParamReprAssetTypeMapping))
			}
		}
	} else {
		s, ok := maybeParamReprAssetTypeMapping.(*[]*ParamReprAssetTypeMapping)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeParamReprAssetTypeMapping))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &paramReprAssetTypeMappingR{}
		}
		args[object.ParamReprID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &paramReprAssetTypeMappingR{}
			}

			args[obj.ParamReprID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`param_repr`),
		qm.WhereIn(`param_repr.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ParamRepr")
	}

	var resultSlice []*ParamRepr
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ParamRepr")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for param_repr")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for param_repr")
	}

	if len(paramReprAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ParamRepr = foreign
		if foreign.R == nil {
			foreign.R = &paramReprR{}
		}
		foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ParamReprID == foreign.ID {
				local.R.ParamRepr = foreign
				if foreign.R == nil {
					foreign.R = &paramReprR{}
				}
				foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, local)
				break
			}
		}
	}

	return nil
}

// LoadParamType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (paramReprAssetTypeMappingL) LoadParamType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeParamReprAssetTypeMapping interface{}, mods queries.Applicator) error {
	var slice []*ParamReprAssetTypeMapping
	var object *ParamReprAssetTypeMapping

	if singular {
		var ok bool
		object, ok = maybeParamReprAssetTypeMapping.(*ParamReprAssetTypeMapping)
		if !ok {
			object = new(ParamReprAssetTypeMapping)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeParamReprAssetTypeMapping))
			}
		}
	} else {
		s, ok := maybeParamReprAssetTypeMapping.(*[]*ParamReprAssetTypeMapping)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeParamReprAssetTypeMapping)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeParamReprAssetTypeMapping))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &paramReprAssetTypeMappingR{}
		}
		args[object.ParamTypeID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &paramReprAssetTypeMappingR{}
			}

			args[obj.ParamTypeID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`param_type`),
		qm.WhereIn(`param_type.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ParamType")
	}

	var resultSlice []*ParamType
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ParamType")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for param_type")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for param_type")
	}

	if len(paramTypeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ParamType = foreign
		if foreign.R == nil {
			foreign.R = &paramTypeR{}
		}
		foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ParamTypeID == foreign.ID {
				local.R.ParamType = foreign
				if foreign.R == nil {
					foreign.R = &paramTypeR{}
				}
				foreign.R.ParamReprAssetTypeMappings = append(foreign.R.ParamReprAssetTypeMappings, local)
				break
			}
		}
	}

	return nil
}

// SetAssetTypeG of the paramReprAssetTypeMapping to the related item.
// Sets o.R.AssetType to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
// Uses the global database handle.
func (o *ParamReprAssetTypeMapping) SetAssetTypeG(ctx context.Context, insert bool, related *AssetType) error {
	return o.SetAssetType(ctx, boil.GetContextDB(), insert, related)
}

// SetAssetType of the paramReprAssetTypeMapping to the related item.
// Sets o.R.AssetType to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
func (o *ParamReprAssetTypeMapping) SetAssetType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AssetType) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"asset_type_id"}),
		strmangle.WhereClause("\"", "\"", 2, paramReprAssetTypeMappingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AssetTypeID = related.ID
	if o.R == nil {
		o.R = &paramReprAssetTypeMappingR{
			AssetType: related,
		}
	} else {
		o.R.AssetType = related
	}

	if related.R == nil {
		related.R = &assetTypeR{
			ParamReprAssetTypeMappings: ParamReprAssetTypeMappingSlice{o},
		}
	} else {
		related.R.ParamReprAssetTypeMappings = append(related.R.ParamReprAssetTypeMappings, o)
	}

	return nil
}

// SetOriginatorClassG of the paramReprAssetTypeMapping to the related item.
// Sets o.R.OriginatorClass to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
// Uses the global database handle.
func (o *ParamReprAssetTypeMapping) SetOriginatorClassG(ctx context.Context, insert bool, related *OriginatorClass) error {
	return o.SetOriginatorClass(ctx, boil.GetContextDB(), insert, related)
}

// SetOriginatorClass of the paramReprAssetTypeMapping to the related item.
// Sets o.R.OriginatorClass to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
func (o *ParamReprAssetTypeMapping) SetOriginatorClass(ctx context.Context, exec boil.ContextExecutor, insert bool, related *OriginatorClass) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"originator_class_id"}),
		strmangle.WhereClause("\"", "\"", 2, paramReprAssetTypeMappingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.OriginatorClassID = related.ID
	if o.R == nil {
		o.R = &paramReprAssetTypeMappingR{
			OriginatorClass: related,
		}
	} else {
		o.R.OriginatorClass = related
	}

	if related.R == nil {
		related.R = &originatorClassR{
			ParamReprAssetTypeMappings: ParamReprAssetTypeMappingSlice{o},
		}
	} else {
		related.R.ParamReprAssetTypeMappings = append(related.R.ParamReprAssetTypeMappings, o)
	}

	return nil
}

// SetParamReprG of the paramReprAssetTypeMapping to the related item.
// Sets o.R.ParamRepr to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
// Uses the global database handle.
func (o *ParamReprAssetTypeMapping) SetParamReprG(ctx context.Context, insert bool, related *ParamRepr) error {
	return o.SetParamRepr(ctx, boil.GetContextDB(), insert, related)
}

// SetParamRepr of the paramReprAssetTypeMapping to the related item.
// Sets o.R.ParamRepr to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
func (o *ParamReprAssetTypeMapping) SetParamRepr(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ParamRepr) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"param_repr_id"}),
		strmangle.WhereClause("\"", "\"", 2, paramReprAssetTypeMappingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ParamReprID = related.ID
	if o.R == nil {
		o.R = &paramReprAssetTypeMappingR{
			ParamRepr: related,
		}
	} else {
		o.R.ParamRepr = related
	}

	if related.R == nil {
		related.R = &paramReprR{
			ParamReprAssetTypeMappings: ParamReprAssetTypeMappingSlice{o},
		}
	} else {
		related.R.ParamReprAssetTypeMappings = append(related.R.ParamReprAssetTypeMappings, o)
	}

	return nil
}

// SetParamTypeG of the paramReprAssetTypeMapping to the related item.
// Sets o.R.ParamType to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
// Uses the global database handle.
func (o *ParamReprAssetTypeMapping) SetParamTypeG(ctx context.Context, insert bool, related *ParamType) error {
	return o.SetParamType(ctx, boil.GetContextDB(), insert, related)
}

// SetParamType of the paramReprAssetTypeMapping to the related item.
// Sets o.R.ParamType to related.
// Adds o to related.R.ParamReprAssetTypeMappings.
func (o *ParamReprAssetTypeMapping) SetParamType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ParamType) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"param_type_id"}),
		strmangle.WhereClause("\"", "\"", 2, paramReprAssetTypeMappingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ParamTypeID = related.ID
	if o.R == nil {
		o.R = &paramReprAssetTypeMappingR{
			ParamType: related,
		}
	} else {
		o.R.ParamType = related
	}

	if related.R == nil {
		related.R = &paramTypeR{
			ParamReprAssetTypeMappings: ParamReprAssetTypeMappingSlice{o},
		}
	} else {
		related.R.ParamReprAssetTypeMappings = append(related.R.ParamReprAssetTypeMappings, o)
	}

	return nil
}

// ParamReprAssetTypeMappings retrieves all the records using an executor.
func ParamReprAssetTypeMappings(mods ...qm.QueryMod) paramReprAssetTypeMappingQuery {
	mods = append(mods, qm.From("\"param_repr_asset_type_mapping\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"param_repr_asset_type_mapping\".*"})
	}

	return paramReprAssetTypeMappingQuery{q}
}

// FindParamReprAssetTypeMappingG retrieves a single record by ID.
func FindParamReprAssetTypeMappingG(ctx context.Context, iD int, selectCols ...string) (*ParamReprAssetTypeMapping, error) {
	return FindParamReprAssetTypeMapping(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindParamReprAssetTypeMapping retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindParamReprAssetTypeMapping(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*ParamReprAssetTypeMapping, error) {
	paramReprAssetTypeMappingObj := &ParamReprAssetTypeMapping{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"param_repr_asset_type_mapping\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, paramReprAssetTypeMappingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from param_repr_asset_type_mapping")
	}

	if err = paramReprAssetTypeMappingObj.doAfterSelectHooks(ctx, exec); err != nil {
		return paramReprAssetTypeMappingObj, err
	}

	return paramReprAssetTypeMappingObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ParamReprAssetTypeMapping) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ParamReprAssetTypeMapping) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no param_repr_asset_type_mapping provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(paramReprAssetTypeMappingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	paramReprAssetTypeMappingInsertCacheMut.RLock()
	cache, cached := paramReprAssetTypeMappingInsertCache[key]
	paramReprAssetTypeMappingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			paramReprAssetTypeMappingAllColumns,
			paramReprAssetTypeMappingColumnsWithDefault,
			paramReprAssetTypeMappingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(paramReprAssetTypeMappingType, paramReprAssetTypeMappingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(paramReprAssetTypeMappingType, paramReprAssetTypeMappingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"param_repr_asset_type_mapping\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"param_repr_asset_type_mapping\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into param_repr_asset_type_mapping")
	}

	if !cached {
		paramReprAssetTypeMappingInsertCacheMut.Lock()
		paramReprAssetTypeMappingInsertCache[key] = cache
		paramReprAssetTypeMappingInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single ParamReprAssetTypeMapping record using the global executor.
// See Update for more documentation.
func (o *ParamReprAssetTypeMapping) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ParamReprAssetTypeMapping.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ParamReprAssetTypeMapping) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	paramReprAssetTypeMappingUpdateCacheMut.RLock()
	cache, cached := paramReprAssetTypeMappingUpdateCache[key]
	paramReprAssetTypeMappingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			paramReprAssetTypeMappingAllColumns,
			paramReprAssetTypeMappingPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update param_repr_asset_type_mapping, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, paramReprAssetTypeMappingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(paramReprAssetTypeMappingType, paramReprAssetTypeMappingMapping, append(wl, paramReprAssetTypeMappingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update param_repr_asset_type_mapping row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for param_repr_asset_type_mapping")
	}

	if !cached {
		paramReprAssetTypeMappingUpdateCacheMut.Lock()
		paramReprAssetTypeMappingUpdateCache[key] = cache
		paramReprAssetTypeMappingUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q paramReprAssetTypeMappingQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q paramReprAssetTypeMappingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for param_repr_asset_type_mapping")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for param_repr_asset_type_mapping")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ParamReprAssetTypeMappingSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ParamReprAssetTypeMappingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paramReprAssetTypeMappingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"param_repr_asset_type_mapping\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, paramReprAssetTypeMappingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in paramReprAssetTypeMapping slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all paramReprAssetTypeMapping")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ParamReprAssetTypeMapping) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ParamReprAssetTypeMapping) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no param_repr_asset_type_mapping provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(paramReprAssetTypeMappingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	paramReprAssetTypeMappingUpsertCacheMut.RLock()
	cache, cached := paramReprAssetTypeMappingUpsertCache[key]
	paramReprAssetTypeMappingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			paramReprAssetTypeMappingAllColumns,
			paramReprAssetTypeMappingColumnsWithDefault,
			paramReprAssetTypeMappingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			paramReprAssetTypeMappingAllColumns,
			paramReprAssetTypeMappingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert param_repr_asset_type_mapping, could not build update column list")
		}

		ret := strmangle.SetComplement(paramReprAssetTypeMappingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(paramReprAssetTypeMappingPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert param_repr_asset_type_mapping, could not build conflict column list")
			}

			conflict = make([]string, len(paramReprAssetTypeMappingPrimaryKeyColumns))
			copy(conflict, paramReprAssetTypeMappingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"param_repr_asset_type_mapping\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(paramReprAssetTypeMappingType, paramReprAssetTypeMappingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(paramReprAssetTypeMappingType, paramReprAssetTypeMappingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert param_repr_asset_type_mapping")
	}

	if !cached {
		paramReprAssetTypeMappingUpsertCacheMut.Lock()
		paramReprAssetTypeMappingUpsertCache[key] = cache
		paramReprAssetTypeMappingUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single ParamReprAssetTypeMapping record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ParamReprAssetTypeMapping) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ParamReprAssetTypeMapping record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ParamReprAssetTypeMapping) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ParamReprAssetTypeMapping provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), paramReprAssetTypeMappingPrimaryKeyMapping)
	sql := "DELETE FROM \"param_repr_asset_type_mapping\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from param_repr_asset_type_mapping")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for param_repr_asset_type_mapping")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q paramReprAssetTypeMappingQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q paramReprAssetTypeMappingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no paramReprAssetTypeMappingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from param_repr_asset_type_mapping")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for param_repr_asset_type_mapping")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ParamReprAssetTypeMappingSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ParamReprAssetTypeMappingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(paramReprAssetTypeMappingBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paramReprAssetTypeMappingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"param_repr_asset_type_mapping\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, paramReprAssetTypeMappingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from paramReprAssetTypeMapping slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for param_repr_asset_type_mapping")
	}

	if len(paramReprAssetTypeMappingAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ParamReprAssetTypeMapping) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ParamReprAssetTypeMapping provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ParamReprAssetTypeMapping) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindParamReprAssetTypeMapping(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ParamReprAssetTypeMappingSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ParamReprAssetTypeMappingSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ParamReprAssetTypeMappingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ParamReprAssetTypeMappingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paramReprAssetTypeMappingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"param_repr_asset_type_mapping\".* FROM \"param_repr_asset_type_mapping\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, paramReprAssetTypeMappingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ParamReprAssetTypeMappingSlice")
	}

	*o = slice

	return nil
}

// ParamReprAssetTypeMappingExistsG checks if the ParamReprAssetTypeMapping row exists.
func ParamReprAssetTypeMappingExistsG(ctx context.Context, iD int) (bool, error) {
	return ParamReprAssetTypeMappingExists(ctx, boil.GetContextDB(), iD)
}

// ParamReprAssetTypeMappingExists checks if the ParamReprAssetTypeMapping row exists.
func ParamReprAssetTypeMappingExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"param_repr_asset_type_mapping\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if param_repr_asset_type_mapping exists")
	}

	return exists, nil
}

// Exists checks if the ParamReprAssetTypeMapping row exists.
func (o *ParamReprAssetTypeMapping) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ParamReprAssetTypeMappingExists(ctx, exec, o.ID)
}
