// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ParamView is an object representing the database table.
type ParamView struct {
	ID                   null.Int    `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	ParamTypeID          null.Int    `boil:"param_type_id" json:"param_type_id,omitempty" toml:"param_type_id" yaml:"param_type_id,omitempty"`
	ParamReprID          null.Int    `boil:"param_repr_id" json:"param_repr_id,omitempty" toml:"param_repr_id" yaml:"param_repr_id,omitempty"`
	AssetTypeID          null.Int    `boil:"asset_type_id" json:"asset_type_id,omitempty" toml:"asset_type_id" yaml:"asset_type_id,omitempty"`
	OriginatorClassID    null.Int    `boil:"originator_class_id" json:"originator_class_id,omitempty" toml:"originator_class_id" yaml:"originator_class_id,omitempty"`
	AssetTypeCode        null.String `boil:"asset_type_code" json:"asset_type_code,omitempty" toml:"asset_type_code" yaml:"asset_type_code,omitempty"`
	AssetTypeAlias       null.String `boil:"asset_type_alias" json:"asset_type_alias,omitempty" toml:"asset_type_alias" yaml:"asset_type_alias,omitempty"`
	AssetTypeHexCode     null.String `boil:"asset_type_hex_code" json:"asset_type_hex_code,omitempty" toml:"asset_type_hex_code" yaml:"asset_type_hex_code,omitempty"`
	OriginatorClassCode  null.String `boil:"originator_class_code" json:"originator_class_code,omitempty" toml:"originator_class_code" yaml:"originator_class_code,omitempty"`
	OriginatorClassAlias null.String `boil:"originator_class_alias" json:"originator_class_alias,omitempty" toml:"originator_class_alias" yaml:"originator_class_alias,omitempty"`
	ParamTypeCode        null.String `boil:"param_type_code" json:"param_type_code,omitempty" toml:"param_type_code" yaml:"param_type_code,omitempty"`
	ParamTypeAlias       null.String `boil:"param_type_alias" json:"param_type_alias,omitempty" toml:"param_type_alias" yaml:"param_type_alias,omitempty"`
	ParamReprCode        null.String `boil:"param_repr_code" json:"param_repr_code,omitempty" toml:"param_repr_code" yaml:"param_repr_code,omitempty"`
	ParamReprAlias       null.String `boil:"param_repr_alias" json:"param_repr_alias,omitempty" toml:"param_repr_alias" yaml:"param_repr_alias,omitempty"`
	ParamReprIsActive    null.Bool   `boil:"param_repr_is_active" json:"param_repr_is_active,omitempty" toml:"param_repr_is_active" yaml:"param_repr_is_active,omitempty"`
	PridSuffix           null.String `boil:"prid_suffix" json:"prid_suffix,omitempty" toml:"prid_suffix" yaml:"prid_suffix,omitempty"`
}

var ParamViewColumns = struct {
	ID                   string
	ParamTypeID          string
	ParamReprID          string
	AssetTypeID          string
	OriginatorClassID    string
	AssetTypeCode        string
	AssetTypeAlias       string
	AssetTypeHexCode     string
	OriginatorClassCode  string
	OriginatorClassAlias string
	ParamTypeCode        string
	ParamTypeAlias       string
	ParamReprCode        string
	ParamReprAlias       string
	ParamReprIsActive    string
	PridSuffix           string
}{
	ID:                   "id",
	ParamTypeID:          "param_type_id",
	ParamReprID:          "param_repr_id",
	AssetTypeID:          "asset_type_id",
	OriginatorClassID:    "originator_class_id",
	AssetTypeCode:        "asset_type_code",
	AssetTypeAlias:       "asset_type_alias",
	AssetTypeHexCode:     "asset_type_hex_code",
	OriginatorClassCode:  "originator_class_code",
	OriginatorClassAlias: "originator_class_alias",
	ParamTypeCode:        "param_type_code",
	ParamTypeAlias:       "param_type_alias",
	ParamReprCode:        "param_repr_code",
	ParamReprAlias:       "param_repr_alias",
	ParamReprIsActive:    "param_repr_is_active",
	PridSuffix:           "prid_suffix",
}

var ParamViewTableColumns = struct {
	ID                   string
	ParamTypeID          string
	ParamReprID          string
	AssetTypeID          string
	OriginatorClassID    string
	AssetTypeCode        string
	AssetTypeAlias       string
	AssetTypeHexCode     string
	OriginatorClassCode  string
	OriginatorClassAlias string
	ParamTypeCode        string
	ParamTypeAlias       string
	ParamReprCode        string
	ParamReprAlias       string
	ParamReprIsActive    string
	PridSuffix           string
}{
	ID:                   "param_view.id",
	ParamTypeID:          "param_view.param_type_id",
	ParamReprID:          "param_view.param_repr_id",
	AssetTypeID:          "param_view.asset_type_id",
	OriginatorClassID:    "param_view.originator_class_id",
	AssetTypeCode:        "param_view.asset_type_code",
	AssetTypeAlias:       "param_view.asset_type_alias",
	AssetTypeHexCode:     "param_view.asset_type_hex_code",
	OriginatorClassCode:  "param_view.originator_class_code",
	OriginatorClassAlias: "param_view.originator_class_alias",
	ParamTypeCode:        "param_view.param_type_code",
	ParamTypeAlias:       "param_view.param_type_alias",
	ParamReprCode:        "param_view.param_repr_code",
	ParamReprAlias:       "param_view.param_repr_alias",
	ParamReprIsActive:    "param_view.param_repr_is_active",
	PridSuffix:           "param_view.prid_suffix",
}

// Generated where

var ParamViewWhere = struct {
	ID                   whereHelpernull_Int
	ParamTypeID          whereHelpernull_Int
	ParamReprID          whereHelpernull_Int
	AssetTypeID          whereHelpernull_Int
	OriginatorClassID    whereHelpernull_Int
	AssetTypeCode        whereHelpernull_String
	AssetTypeAlias       whereHelpernull_String
	AssetTypeHexCode     whereHelpernull_String
	OriginatorClassCode  whereHelpernull_String
	OriginatorClassAlias whereHelpernull_String
	ParamTypeCode        whereHelpernull_String
	ParamTypeAlias       whereHelpernull_String
	ParamReprCode        whereHelpernull_String
	ParamReprAlias       whereHelpernull_String
	ParamReprIsActive    whereHelpernull_Bool
	PridSuffix           whereHelpernull_String
}{
	ID:                   whereHelpernull_Int{field: "\"param_view\".\"id\""},
	ParamTypeID:          whereHelpernull_Int{field: "\"param_view\".\"param_type_id\""},
	ParamReprID:          whereHelpernull_Int{field: "\"param_view\".\"param_repr_id\""},
	AssetTypeID:          whereHelpernull_Int{field: "\"param_view\".\"asset_type_id\""},
	OriginatorClassID:    whereHelpernull_Int{field: "\"param_view\".\"originator_class_id\""},
	AssetTypeCode:        whereHelpernull_String{field: "\"param_view\".\"asset_type_code\""},
	AssetTypeAlias:       whereHelpernull_String{field: "\"param_view\".\"asset_type_alias\""},
	AssetTypeHexCode:     whereHelpernull_String{field: "\"param_view\".\"asset_type_hex_code\""},
	OriginatorClassCode:  whereHelpernull_String{field: "\"param_view\".\"originator_class_code\""},
	OriginatorClassAlias: whereHelpernull_String{field: "\"param_view\".\"originator_class_alias\""},
	ParamTypeCode:        whereHelpernull_String{field: "\"param_view\".\"param_type_code\""},
	ParamTypeAlias:       whereHelpernull_String{field: "\"param_view\".\"param_type_alias\""},
	ParamReprCode:        whereHelpernull_String{field: "\"param_view\".\"param_repr_code\""},
	ParamReprAlias:       whereHelpernull_String{field: "\"param_view\".\"param_repr_alias\""},
	ParamReprIsActive:    whereHelpernull_Bool{field: "\"param_view\".\"param_repr_is_active\""},
	PridSuffix:           whereHelpernull_String{field: "\"param_view\".\"prid_suffix\""},
}

var (
	paramViewAllColumns            = []string{"id", "param_type_id", "param_repr_id", "asset_type_id", "originator_class_id", "asset_type_code", "asset_type_alias", "asset_type_hex_code", "originator_class_code", "originator_class_alias", "param_type_code", "param_type_alias", "param_repr_code", "param_repr_alias", "param_repr_is_active", "prid_suffix"}
	paramViewColumnsWithoutDefault = []string{}
	paramViewColumnsWithDefault    = []string{"id", "param_type_id", "param_repr_id", "asset_type_id", "originator_class_id", "asset_type_code", "asset_type_alias", "asset_type_hex_code", "originator_class_code", "originator_class_alias", "param_type_code", "param_type_alias", "param_repr_code", "param_repr_alias", "param_repr_is_active", "prid_suffix"}
	paramViewPrimaryKeyColumns     = []string{}
	paramViewGeneratedColumns      = []string{}
)

type (
	// ParamViewSlice is an alias for a slice of pointers to ParamView.
	// This should almost always be used instead of []ParamView.
	ParamViewSlice []*ParamView
	// ParamViewHook is the signature for custom ParamView hook methods
	ParamViewHook func(context.Context, boil.ContextExecutor, *ParamView) error

	paramViewQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	paramViewType           = reflect.TypeOf(&ParamView{})
	paramViewMapping        = queries.MakeStructMapping(paramViewType)
	paramViewInsertCacheMut sync.RWMutex
	paramViewInsertCache    = make(map[string]insertCache)
	paramViewUpdateCacheMut sync.RWMutex
	paramViewUpdateCache    = make(map[string]updateCache)
	paramViewUpsertCacheMut sync.RWMutex
	paramViewUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var paramViewAfterSelectMu sync.Mutex
var paramViewAfterSelectHooks []ParamViewHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ParamView) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paramViewAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddParamViewHook registers your hook function for all future operations.
func AddParamViewHook(hookPoint boil.HookPoint, paramViewHook ParamViewHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		paramViewAfterSelectMu.Lock()
		paramViewAfterSelectHooks = append(paramViewAfterSelectHooks, paramViewHook)
		paramViewAfterSelectMu.Unlock()
	}
}

// OneG returns a single paramView record from the query using the global executor.
func (q paramViewQuery) OneG(ctx context.Context) (*ParamView, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single paramView record from the query.
func (q paramViewQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ParamView, error) {
	o := &ParamView{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for param_view")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ParamView records from the query using the global executor.
func (q paramViewQuery) AllG(ctx context.Context) (ParamViewSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ParamView records from the query.
func (q paramViewQuery) All(ctx context.Context, exec boil.ContextExecutor) (ParamViewSlice, error) {
	var o []*ParamView

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ParamView slice")
	}

	if len(paramViewAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ParamView records in the query using the global executor
func (q paramViewQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ParamView records in the query.
func (q paramViewQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count param_view rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q paramViewQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q paramViewQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if param_view exists")
	}

	return count > 0, nil
}

// ParamViews retrieves all the records using an executor.
func ParamViews(mods ...qm.QueryMod) paramViewQuery {
	mods = append(mods, qm.From("\"param_view\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"param_view\".*"})
	}

	return paramViewQuery{q}
}
