// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/client.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForecastingService_Preprocess_FullMethodName      = "/forecasting.ForecastingService/Preprocess"
	ForecastingService_Train_FullMethodName           = "/forecasting.ForecastingService/Train"
	ForecastingService_Forecast_FullMethodName        = "/forecasting.ForecastingService/Forecast"
	ForecastingService_Retrain_FullMethodName         = "/forecasting.ForecastingService/Retrain"
	ForecastingService_GetModelDetails_FullMethodName = "/forecasting.ForecastingService/GetModelDetails"
	ForecastingService_ListModels_FullMethodName      = "/forecasting.ForecastingService/ListModels"
	ForecastingService_DeleteModel_FullMethodName     = "/forecasting.ForecastingService/DeleteModel"
	ForecastingService_HealthCheck_FullMethodName     = "/forecasting.ForecastingService/HealthCheck"
)

// ForecastingServiceClient is the client API for ForecastingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForecastingServiceClient interface {
	// Data preprocessing
	Preprocess(ctx context.Context, in *PreprocessRequest, opts ...grpc.CallOption) (*PreprocessResponse, error)
	Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResponse, error)
	Retrain(ctx context.Context, in *RetrainRequest, opts ...grpc.CallOption) (*RetrainResponse, error)
	// common model management
	GetModelDetails(ctx context.Context, in *ModelDetailsRequest, opts ...grpc.CallOption) (*ModelDetailsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type forecastingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForecastingServiceClient(cc grpc.ClientConnInterface) ForecastingServiceClient {
	return &forecastingServiceClient{cc}
}

func (c *forecastingServiceClient) Preprocess(ctx context.Context, in *PreprocessRequest, opts ...grpc.CallOption) (*PreprocessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreprocessResponse)
	err := c.cc.Invoke(ctx, ForecastingService_Preprocess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, ForecastingService_Train_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) Forecast(ctx context.Context, in *ForecastRequest, opts ...grpc.CallOption) (*ForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForecastResponse)
	err := c.cc.Invoke(ctx, ForecastingService_Forecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) Retrain(ctx context.Context, in *RetrainRequest, opts ...grpc.CallOption) (*RetrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrainResponse)
	err := c.cc.Invoke(ctx, ForecastingService_Retrain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) GetModelDetails(ctx context.Context, in *ModelDetailsRequest, opts ...grpc.CallOption) (*ModelDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelDetailsResponse)
	err := c.cc.Invoke(ctx, ForecastingService_GetModelDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ForecastingService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, ForecastingService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastingServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ForecastingService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecastingServiceServer is the server API for ForecastingService service.
// All implementations must embed UnimplementedForecastingServiceServer
// for forward compatibility.
type ForecastingServiceServer interface {
	// Data preprocessing
	Preprocess(context.Context, *PreprocessRequest) (*PreprocessResponse, error)
	Train(context.Context, *TrainRequest) (*TrainResponse, error)
	Forecast(context.Context, *ForecastRequest) (*ForecastResponse, error)
	Retrain(context.Context, *RetrainRequest) (*RetrainResponse, error)
	// common model management
	GetModelDetails(context.Context, *ModelDetailsRequest) (*ModelDetailsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedForecastingServiceServer()
}

// UnimplementedForecastingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForecastingServiceServer struct{}

func (UnimplementedForecastingServiceServer) Preprocess(context.Context, *PreprocessRequest) (*PreprocessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Preprocess not implemented")
}
func (UnimplementedForecastingServiceServer) Train(context.Context, *TrainRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedForecastingServiceServer) Forecast(context.Context, *ForecastRequest) (*ForecastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forecast not implemented")
}
func (UnimplementedForecastingServiceServer) Retrain(context.Context, *RetrainRequest) (*RetrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrain not implemented")
}
func (UnimplementedForecastingServiceServer) GetModelDetails(context.Context, *ModelDetailsRequest) (*ModelDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelDetails not implemented")
}
func (UnimplementedForecastingServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedForecastingServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedForecastingServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedForecastingServiceServer) mustEmbedUnimplementedForecastingServiceServer() {}
func (UnimplementedForecastingServiceServer) testEmbeddedByValue()                            {}

// UnsafeForecastingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecastingServiceServer will
// result in compilation errors.
type UnsafeForecastingServiceServer interface {
	mustEmbedUnimplementedForecastingServiceServer()
}

func RegisterForecastingServiceServer(s grpc.ServiceRegistrar, srv ForecastingServiceServer) {
	// If the following call panics, it indicates UnimplementedForecastingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForecastingService_ServiceDesc, srv)
}

func _ForecastingService_Preprocess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreprocessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).Preprocess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_Preprocess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).Preprocess(ctx, req.(*PreprocessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_Train_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).Train(ctx, req.(*TrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_Forecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).Forecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_Forecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).Forecast(ctx, req.(*ForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_Retrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).Retrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_Retrain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).Retrain(ctx, req.(*RetrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_GetModelDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).GetModelDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_GetModelDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).GetModelDetails(ctx, req.(*ModelDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastingServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForecastingService_ServiceDesc is the grpc.ServiceDesc for ForecastingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForecastingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forecasting.ForecastingService",
	HandlerType: (*ForecastingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Preprocess",
			Handler:    _ForecastingService_Preprocess_Handler,
		},
		{
			MethodName: "Train",
			Handler:    _ForecastingService_Train_Handler,
		},
		{
			MethodName: "Forecast",
			Handler:    _ForecastingService_Forecast_Handler,
		},
		{
			MethodName: "Retrain",
			Handler:    _ForecastingService_Retrain_Handler,
		},
		{
			MethodName: "GetModelDetails",
			Handler:    _ForecastingService_GetModelDetails_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ForecastingService_ListModels_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _ForecastingService_DeleteModel_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ForecastingService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client.proto",
}

const (
	ClassificationService_GenerateLabels_FullMethodName    = "/forecasting.ClassificationService/GenerateLabels"
	ClassificationService_Train_FullMethodName             = "/forecasting.ClassificationService/Train"
	ClassificationService_Predict_FullMethodName           = "/forecasting.ClassificationService/Predict"
	ClassificationService_RetrainClassifier_FullMethodName = "/forecasting.ClassificationService/RetrainClassifier"
	ClassificationService_GetModelDetails_FullMethodName   = "/forecasting.ClassificationService/GetModelDetails"
	ClassificationService_ListModels_FullMethodName        = "/forecasting.ClassificationService/ListModels"
	ClassificationService_DeleteModel_FullMethodName       = "/forecasting.ClassificationService/DeleteModel"
	ClassificationService_HealthCheck_FullMethodName       = "/forecasting.ClassificationService/HealthCheck"
)

// ClassificationServiceClient is the client API for ClassificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassificationServiceClient interface {
	// Data labeling
	GenerateLabels(ctx context.Context, in *LabelRequest, opts ...grpc.CallOption) (*LabelResponse, error)
	Train(ctx context.Context, in *ClassifierTrainRequest, opts ...grpc.CallOption) (*ClassifierTrainResponse, error)
	Predict(ctx context.Context, in *ClassifierPredictRequest, opts ...grpc.CallOption) (*ClassifierPredictResponse, error)
	RetrainClassifier(ctx context.Context, in *RetrainClassifierRequest, opts ...grpc.CallOption) (*RetrainClassifierResponse, error)
	// common model management
	GetModelDetails(ctx context.Context, in *ModelDetailsRequest, opts ...grpc.CallOption) (*ModelDetailsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type classificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassificationServiceClient(cc grpc.ClientConnInterface) ClassificationServiceClient {
	return &classificationServiceClient{cc}
}

func (c *classificationServiceClient) GenerateLabels(ctx context.Context, in *LabelRequest, opts ...grpc.CallOption) (*LabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LabelResponse)
	err := c.cc.Invoke(ctx, ClassificationService_GenerateLabels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) Train(ctx context.Context, in *ClassifierTrainRequest, opts ...grpc.CallOption) (*ClassifierTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifierTrainResponse)
	err := c.cc.Invoke(ctx, ClassificationService_Train_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) Predict(ctx context.Context, in *ClassifierPredictRequest, opts ...grpc.CallOption) (*ClassifierPredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifierPredictResponse)
	err := c.cc.Invoke(ctx, ClassificationService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) RetrainClassifier(ctx context.Context, in *RetrainClassifierRequest, opts ...grpc.CallOption) (*RetrainClassifierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrainClassifierResponse)
	err := c.cc.Invoke(ctx, ClassificationService_RetrainClassifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) GetModelDetails(ctx context.Context, in *ModelDetailsRequest, opts ...grpc.CallOption) (*ModelDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelDetailsResponse)
	err := c.cc.Invoke(ctx, ClassificationService_GetModelDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ClassificationService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, ClassificationService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classificationServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ClassificationService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassificationServiceServer is the server API for ClassificationService service.
// All implementations must embed UnimplementedClassificationServiceServer
// for forward compatibility.
type ClassificationServiceServer interface {
	// Data labeling
	GenerateLabels(context.Context, *LabelRequest) (*LabelResponse, error)
	Train(context.Context, *ClassifierTrainRequest) (*ClassifierTrainResponse, error)
	Predict(context.Context, *ClassifierPredictRequest) (*ClassifierPredictResponse, error)
	RetrainClassifier(context.Context, *RetrainClassifierRequest) (*RetrainClassifierResponse, error)
	// common model management
	GetModelDetails(context.Context, *ModelDetailsRequest) (*ModelDetailsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedClassificationServiceServer()
}

// UnimplementedClassificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassificationServiceServer struct{}

func (UnimplementedClassificationServiceServer) GenerateLabels(context.Context, *LabelRequest) (*LabelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateLabels not implemented")
}
func (UnimplementedClassificationServiceServer) Train(context.Context, *ClassifierTrainRequest) (*ClassifierTrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedClassificationServiceServer) Predict(context.Context, *ClassifierPredictRequest) (*ClassifierPredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedClassificationServiceServer) RetrainClassifier(context.Context, *RetrainClassifierRequest) (*RetrainClassifierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrainClassifier not implemented")
}
func (UnimplementedClassificationServiceServer) GetModelDetails(context.Context, *ModelDetailsRequest) (*ModelDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelDetails not implemented")
}
func (UnimplementedClassificationServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedClassificationServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedClassificationServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedClassificationServiceServer) mustEmbedUnimplementedClassificationServiceServer() {}
func (UnimplementedClassificationServiceServer) testEmbeddedByValue()                               {}

// UnsafeClassificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassificationServiceServer will
// result in compilation errors.
type UnsafeClassificationServiceServer interface {
	mustEmbedUnimplementedClassificationServiceServer()
}

func RegisterClassificationServiceServer(s grpc.ServiceRegistrar, srv ClassificationServiceServer) {
	// If the following call panics, it indicates UnimplementedClassificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassificationService_ServiceDesc, srv)
}

func _ClassificationService_GenerateLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).GenerateLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_GenerateLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).GenerateLabels(ctx, req.(*LabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifierTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_Train_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).Train(ctx, req.(*ClassifierTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifierPredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).Predict(ctx, req.(*ClassifierPredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_RetrainClassifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrainClassifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).RetrainClassifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_RetrainClassifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).RetrainClassifier(ctx, req.(*RetrainClassifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_GetModelDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).GetModelDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_GetModelDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).GetModelDetails(ctx, req.(*ModelDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassificationService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassificationService_ServiceDesc is the grpc.ServiceDesc for ClassificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forecasting.ClassificationService",
	HandlerType: (*ClassificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateLabels",
			Handler:    _ClassificationService_GenerateLabels_Handler,
		},
		{
			MethodName: "Train",
			Handler:    _ClassificationService_Train_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _ClassificationService_Predict_Handler,
		},
		{
			MethodName: "RetrainClassifier",
			Handler:    _ClassificationService_RetrainClassifier_Handler,
		},
		{
			MethodName: "GetModelDetails",
			Handler:    _ClassificationService_GetModelDetails_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ClassificationService_ListModels_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _ClassificationService_DeleteModel_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ClassificationService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client.proto",
}

const (
	AnomalyService_Train_FullMethodName           = "/forecasting.AnomalyService/Train"
	AnomalyService_Predict_FullMethodName         = "/forecasting.AnomalyService/Predict"
	AnomalyService_RetrainAnomaly_FullMethodName  = "/forecasting.AnomalyService/RetrainAnomaly"
	AnomalyService_GetModelDetails_FullMethodName = "/forecasting.AnomalyService/GetModelDetails"
	AnomalyService_ListModels_FullMethodName      = "/forecasting.AnomalyService/ListModels"
	AnomalyService_DeleteModel_FullMethodName     = "/forecasting.AnomalyService/DeleteModel"
	AnomalyService_HealthCheck_FullMethodName     = "/forecasting.AnomalyService/HealthCheck"
)

// AnomalyServiceClient is the client API for AnomalyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnomalyServiceClient interface {
	Train(ctx context.Context, in *AnomalyTrainRequest, opts ...grpc.CallOption) (*AnomalyTrainResponse, error)
	Predict(ctx context.Context, in *AnomalyPredictRequest, opts ...grpc.CallOption) (*AnomalyPredictResponse, error)
	RetrainAnomaly(ctx context.Context, in *AnomalyReTrainRequest, opts ...grpc.CallOption) (*AnomalyReTrainResponse, error)
	// common model management
	GetModelDetails(ctx context.Context, in *ModelDetailsRequest, opts ...grpc.CallOption) (*ModelDetailsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type anomalyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnomalyServiceClient(cc grpc.ClientConnInterface) AnomalyServiceClient {
	return &anomalyServiceClient{cc}
}

func (c *anomalyServiceClient) Train(ctx context.Context, in *AnomalyTrainRequest, opts ...grpc.CallOption) (*AnomalyTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnomalyTrainResponse)
	err := c.cc.Invoke(ctx, AnomalyService_Train_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyServiceClient) Predict(ctx context.Context, in *AnomalyPredictRequest, opts ...grpc.CallOption) (*AnomalyPredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnomalyPredictResponse)
	err := c.cc.Invoke(ctx, AnomalyService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyServiceClient) RetrainAnomaly(ctx context.Context, in *AnomalyReTrainRequest, opts ...grpc.CallOption) (*AnomalyReTrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnomalyReTrainResponse)
	err := c.cc.Invoke(ctx, AnomalyService_RetrainAnomaly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyServiceClient) GetModelDetails(ctx context.Context, in *ModelDetailsRequest, opts ...grpc.CallOption) (*ModelDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelDetailsResponse)
	err := c.cc.Invoke(ctx, AnomalyService_GetModelDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, AnomalyService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, AnomalyService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anomalyServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AnomalyService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnomalyServiceServer is the server API for AnomalyService service.
// All implementations must embed UnimplementedAnomalyServiceServer
// for forward compatibility.
type AnomalyServiceServer interface {
	Train(context.Context, *AnomalyTrainRequest) (*AnomalyTrainResponse, error)
	Predict(context.Context, *AnomalyPredictRequest) (*AnomalyPredictResponse, error)
	RetrainAnomaly(context.Context, *AnomalyReTrainRequest) (*AnomalyReTrainResponse, error)
	// common model management
	GetModelDetails(context.Context, *ModelDetailsRequest) (*ModelDetailsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAnomalyServiceServer()
}

// UnimplementedAnomalyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnomalyServiceServer struct{}

func (UnimplementedAnomalyServiceServer) Train(context.Context, *AnomalyTrainRequest) (*AnomalyTrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedAnomalyServiceServer) Predict(context.Context, *AnomalyPredictRequest) (*AnomalyPredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedAnomalyServiceServer) RetrainAnomaly(context.Context, *AnomalyReTrainRequest) (*AnomalyReTrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrainAnomaly not implemented")
}
func (UnimplementedAnomalyServiceServer) GetModelDetails(context.Context, *ModelDetailsRequest) (*ModelDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelDetails not implemented")
}
func (UnimplementedAnomalyServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAnomalyServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedAnomalyServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAnomalyServiceServer) mustEmbedUnimplementedAnomalyServiceServer() {}
func (UnimplementedAnomalyServiceServer) testEmbeddedByValue()                        {}

// UnsafeAnomalyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnomalyServiceServer will
// result in compilation errors.
type UnsafeAnomalyServiceServer interface {
	mustEmbedUnimplementedAnomalyServiceServer()
}

func RegisterAnomalyServiceServer(s grpc.ServiceRegistrar, srv AnomalyServiceServer) {
	// If the following call panics, it indicates UnimplementedAnomalyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnomalyService_ServiceDesc, srv)
}

func _AnomalyService_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnomalyTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_Train_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).Train(ctx, req.(*AnomalyTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnomalyPredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).Predict(ctx, req.(*AnomalyPredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyService_RetrainAnomaly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnomalyReTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).RetrainAnomaly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_RetrainAnomaly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).RetrainAnomaly(ctx, req.(*AnomalyReTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyService_GetModelDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).GetModelDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_GetModelDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).GetModelDetails(ctx, req.(*ModelDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnomalyService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnomalyService_ServiceDesc is the grpc.ServiceDesc for AnomalyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnomalyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forecasting.AnomalyService",
	HandlerType: (*AnomalyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Train",
			Handler:    _AnomalyService_Train_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _AnomalyService_Predict_Handler,
		},
		{
			MethodName: "RetrainAnomaly",
			Handler:    _AnomalyService_RetrainAnomaly_Handler,
		},
		{
			MethodName: "GetModelDetails",
			Handler:    _AnomalyService_GetModelDetails_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AnomalyService_ListModels_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _AnomalyService_DeleteModel_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AnomalyService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client.proto",
}
